### ISSUE TITLE
Crash in 0.16.0

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1017]
```
java.lang.IllegalArgumentException: NetworkCallback was not registered
at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3883)
at im.vector.matrix.android.internal.network.PreferredNetworkCallbackStrategy.unregister(NetworkCallbackStrategy.kt:74)
at im.vector.matrix.android.internal.network.DefaultNetworkConnectivityChecker.unbind(NetworkConnectivityChecker.kt:107)
at im.vector.matrix.android.internal.network.DefaultNetworkConnectivityChecker.register(NetworkConnectivityChecker.kt:78)
at im.vector.matrix.android.internal.session.sync.job.SyncThread.run(SyncThread.kt:114)
```

**Comment by bmarty** [comment]
Also
```
Exception: java.lang.IllegalArgumentException: Invalid NetworkCallback
at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3204)
at im.vector.matrix.android.internal.network.PreferredNetworkCallbackStrategy.unregister(NetworkCallbackStrategy.kt:74)
at im.vector.matrix.android.internal.network.DefaultNetworkConnectivityChecker.unbind(NetworkConnectivityChecker.kt:107)
at im.vector.matrix.android.internal.network.DefaultNetworkConnectivityChecker.register(NetworkConnectivityChecker.kt:78)
at im.vector.matrix.android.internal.session.sync.job.SyncThread.run(SyncThread.kt:114)
```

**Comment by bmarty** [comment]
Not seeing anymore this one...
