### ISSUE TITLE
Long message cannot be sent/takes infinite time & blocks other messages

### ISSUE THREAD

**Issue by rugk** [vector-im/element-android#1397]
v0.2.0
SDK 0.0.1
OLM 3.1.2
Android 9

## STR

1. In an encrypted direct message chat, send a message. A long message! (very long)

**What happens:** It does a "sending" status (grey text etc.) all the time, takes an infinite time to send, but does not actually do so

**What should happen:** Send it.

On the desktop Riot client, sending the same message works without problems.

**Additional problem:** This one message now blocks all later messages. All later messages in that chat also go into the "endless loading cycle" mode.
Is there maybe a workaround for that? (okay new chat, but that is annoying) Can't we delete the old message.
Maybe a "cancel sending" button would be useful. (already tried to kill RiotX and restart it, that did not help)

**Comment by bmarty** [comment]
Please define "very long". How many chars does the message contain (roughly)?

**Comment by rugk** [comment]
19 lines, 651 words, 3830 characters

**Comment by bmarty** [comment]
I have no pb sending a message to an encrypted room with 3830 "a".

If you enable developer option in the application setting (in advanced settings section), you will have an extra menu (top right) on the home to clear the sending queue IIRC

**Comment by rugk** [comment]
Thx that workaround did exactly what I wanted to do.

--

As for the problem: Cannot reproduce it with 3830 a's too either. There have to be more criteria.
However, I can reproduce it with the original text.

Aaand with a text of 30 paragraphs of lorem ipsum:
```
Quidem odio labore fuga beatae laboriosam. Aut suscipit quod nemo itaque voluptate. Temporibus architecto a sunt impedit molestiae. Odio quidem ut tenetur modi aspernatur saepe quia velit. Quibusdam ducimus totam distinctio nobis ut. Assumenda nesciunt blanditiis sed necessitatibus similique deleniti.

Harum veniam vitae doloremque quia ut quia iure. Et magnam molestiae totam. Quidem repellendus maiores quod sed sit hic.

Eos dolor est qui iusto quidem. Cum et officiis nemo tempora. Assumenda ipsam maxime quisquam et et.

Neque numquam consequuntur distinctio praesentium. Sed voluptatibus doloribus voluptas voluptatem quam totam. Voluptatem ad consectetur qui sit hic. Asperiores pariatur incidunt sunt aliquid consequuntur qui reprehenderit. Magnam veniam animi illum labore optio.

Blanditiis mollitia quidem quis officiis est cumque. Placeat velit dolorum aut aut molestias ipsa repellat voluptatem. Et sunt cumque laudantium corrupti ullam delectus. Et expedita laborum officia provident omnis eligendi.

Qui quasi quas facilis quam eum. Molestias laborum sunt adipisci nam facere omnis magnam. Accusantium tempora officiis dolorum ut labore exercitationem sed. Fuga aut voluptatum autem.

Qui non neque vel. Aut rerum sapiente necessitatibus voluptatem eius sint et quae. Quaerat labore sed blanditiis. Velit et ut et qui ut a. Provident laudantium et iure animi dolores. Quo voluptatem tenetur id ea aut sapiente.

Aut non laborum reiciendis. Tenetur necessitatibus repellendus reiciendis sit voluptatem quaerat placeat voluptate. Et optio minima sunt dicta eum totam dolorem veritatis. Qui esse necessitatibus molestiae ducimus. Aut sed nihil qui sunt magni explicabo illo temporibus.

Quia voluptatibus nihil magni vero enim velit maiores eos. Nesciunt sunt sequi corporis dolor ratione quo et corporis. Sit voluptas quidem aliquam omnis sed. Sunt neque minus odio tempore. Cum unde fugit at consequuntur animi unde sapiente occaecati.

Nobis delectus sed earum temporibus quia. Maxime occaecati vitae repudiandae consectetur doloribus. Ipsa dolorem quibusdam temporibus doloremque adipisci.

Unde est non ut. Dolor et repudiandae esse aut sit. Voluptas est nobis ullam earum consequatur labore.

Amet ab error omnis ducimus ducimus. Aliquam soluta quia unde autem exercitationem iusto itaque quidem. Sed magnam maiores sit saepe velit sit quaerat. Nobis sequi odit sequi.

Tempore sequi rem quia vitae velit veritatis nihil a. Voluptas quis exercitationem qui quia rerum. Ut sit neque recusandae atque qui nesciunt. Et modi veritatis quis provident architecto. Explicabo repudiandae et asperiores aut minima impedit error voluptatem. Quis sed dolor aspernatur et maxime veniam aut.

Consequatur id ducimus distinctio beatae distinctio. Rerum id est repellendus laudantium illo similique. Qui molestiae est laborum quos voluptatem reiciendis. Similique quia iusto ad rerum omnis quis. Adipisci nobis vel facere est ex repudiandae veniam quos.

Rerum nesciunt nisi explicabo in aliquam. Ut enim dolor aut cumque adipisci. Dolor aspernatur dolores ad et corporis expedita modi rerum. Porro ad est sint voluptate ut similique perferendis.

Consequatur iure doloremque vitae ex maxime aliquam. Qui quia ullam illum numquam ducimus. Explicabo quasi voluptatem et dolorem soluta et. Quos nihil temporibus accusantium voluptatem dolores tempore. Ea sint voluptatibus quam voluptatum. Et saepe possimus quae et est eos sint.

Quibusdam possimus incidunt dolor voluptatum impedit harum. A eos odit pariatur non. Officiis ipsam voluptatem voluptas. Qui consequatur voluptatem quaerat. Et ratione eligendi cumque quos ratione soluta beatae est. Quisquam et expedita officiis maiores molestias enim.

Architecto incidunt ut quo enim earum velit natus. Illum saepe corporis ipsum voluptatem id et ipsum ut. Alias veritatis minima dolorem. Reiciendis reiciendis placeat maxime sed illo nam. Repellendus qui dolorem nostrum reprehenderit. Vero impedit non consequuntur inventore non quia qui.

Inventore placeat illum veritatis sit reprehenderit eveniet exercitationem esse. Vero labore numquam enim alias. Impedit possimus cumque debitis quaerat omnis exercitationem totam. Soluta aut ea ipsam. Consequatur quibusdam est libero totam quisquam deserunt. Ex et et non et veniam minima doloremque qui.

Provident consequatur quod voluptatem quia mollitia veniam. Necessitatibus enim rem aut voluptas. Sit nihil corrupti dolorem. Ad velit voluptas perspiciatis.

Ipsum quis ut culpa corporis est rerum. Ut ea cupiditate non id qui iure. Eveniet fuga voluptatem non.

Delectus consequatur debitis consequatur sunt voluptatibus. Qui dolorum vel voluptatem earum et atque. Voluptas repellat omnis dolor sit suscipit et necessitatibus natus. Repudiandae unde ab qui. Minima rerum numquam magnam esse corporis officia.

Qui fugiat ut et. Ab animi voluptatum et aut qui voluptas. Voluptas tenetur error sit ipsa excepturi mollitia ut nostrum. Est incidunt nobis nulla. Sit eaque minima cumque maxime et aliquam. Temporibus accusamus accusantium ducimus error perferendis perferendis.

Sed blanditiis nulla eos et aut ipsam eaque odio. Fugit veniam laborum dolorum id aperiam amet ratione quia. Id similique aut ea aspernatur. Sequi ratione magnam accusamus laudantium. Aut vero doloremque quo illo voluptatem fugit.

Dolore blanditiis quod qui non. Autem unde molestiae rerum vitae dolores accusamus quam ab. Inventore harum perferendis consectetur repellat.

Doloremque inventore ad ipsum rerum velit ducimus. A sed soluta enim qui aut. Aut alias commodi impedit quibusdam quidem molestiae exercitationem. Dolorum et illo illo omnis qui quae.

Ab pariatur fuga voluptatem. Quisquam voluptatem ut et. Hic laboriosam quas velit. Qui natus soluta temporibus ipsa eaque et rerum. Suscipit distinctio ipsa voluptas qui consequatur eos modi.

Sapiente voluptas fugiat sunt deserunt tempore ut quod. Non sunt sit culpa. Sint libero reprehenderit temporibus architecto repellendus at repellendus. Voluptatibus commodi dolor molestiae ut natus explicabo.

Velit iusto non exercitationem eius. Nisi officiis omnis minus incidunt atque. Asperiores et accusantium excepturi sequi aliquam consequatur.

Asperiores vel accusantium aspernatur et nobis dolore non. Dolorem voluptas possimus quia dolor est dolor. Animi voluptate error sit eum. Vel esse et tenetur.
```

**Comment by TR-SLimey** [comment]
Can confirm the bug. On the note of long messages; when typing one, the message history cannot be viewed if the message exceeds the screen length. It might be useful to keep the text box maximum height slightly smaller than the screen height to make it easier to reply to long messages with long messages.

**Comment by rugk** [comment]
@TR-SLimey  That is a totally valid bug and I know that one too, but it's totally unrelated to this one here. This one here is about the problem that it cannot **send** a message even after pressing send.
Your's is about **composing** a message.

As such, please open a new issue.

**Comment by TR-SLimey** [comment]
@rugk will do. Thanks.

**Comment by steef435** [comment]
Just experienced this while trying to send an article to someone. Then also with some Lorem Ipsum (3.5kb).

The send queue appears to be no longer blocked, other messages go through, but the large text stays at the bottom of the view forever (in grey text). _Clear sending queue_ does not make it go away. (I suppose clearing cache will, going to let it run for a day to see what happens first).

3.5kb is not a lot of data, Signal sent the same message instantly. Do you have any hunch as to where in the code I could look for a cause?

**Comment by BillCarsonFr** [comment]
FTR, it's due to work Data limitation
````
    java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
````
