### ISSUE TITLE
Crash when sending large message (> 10_000 chars)

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1412]
With the following exception:

```
     Caused by: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
        at androidx.work.Data.toByteArray(Data.java:417)
        at androidx.work.Data$Builder.build(Data.java:845)
        at im.vector.matrix.android.internal.session.room.send.DefaultSendService.createEncryptEventWork(DefaultSendService.kt:360)
        at im.vector.matrix.android.internal.session.room.send.DefaultSendService.sendEvent(DefaultSendService.kt:111)
        at im.vector.matrix.android.internal.session.room.send.DefaultSendService.resendTextMessage(DefaultSendService.kt:137)
        at im.vector.matrix.android.internal.session.room.DefaultRoom.resendTextMessage(DefaultRoom.kt)
        at im.vector.riotx.features.home.room.detail.RoomDetailViewModel.handleResendEvent(RoomDetailViewModel.kt:786)
        at im.vector.riotx.features.home.room.detail.RoomDetailViewModel.handle(RoomDetailViewModel.kt:202)
        at im.vector.riotx.features.home.room.detail.RoomDetailFragment.handleActions(RoomDetailFragment.kt:1240)
        at im.vector.riotx.features.home.room.detail.RoomDetailFragment.access$handleActions(RoomDetailFragment.kt:181)
        at im.vector.riotx.features.home.room.detail.RoomDetailFragment$onViewCreated$3.accept(RoomDetailFragment.kt:270)
        at im.vector.riotx.features.home.room.detail.RoomDetailFragment$onViewCreated$3.accept(RoomDetailFragment.kt:181)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201) 
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

I do not think we will be able to fix the crash, but we may avoid crash by limiting the size of the sent text.

P3 as it is a pretty uncommon use case, and I'm the first one to report it :)

Also https://matrix.org/docs/spec/client_server/latest#size-limits exists and is not taken into account at all in RiotX

**Comment by shumvgolove** [comment]
Once upon a time I was writing a huge story to my friend and after sending the message RiotX crashed and everything that I wrote disappeared without a trace (in fact, about half of what I wrote was erased).

It would be nice if RiotX did not allow sending such long messages if it crashes the app entirely, but I think it’s better to fix this problem in general.

**Comment by bmarty** [comment]
We are no storing the sent message in database, and not sent it's content to the worker anymore, so this issue can be close now.
