### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-android#1839]
As soon as I open riotx, it closes again.

logs fromADB:

```
07-29 10:11:10.709 23332 23332 E Zygote  : isWhitelistProcess - Process is Whitelisted
07-29 10:11:10.712 23332 23332 E Zygote  : accessInfo : 1
07-29 10:11:10.722 23332 23332 I tor.riotx.debu: Late-enabling -Xcheck:jni
07-29 10:11:11.091 23332 23332 I MultiDex: VM with version 2.1.0 has multidex support
07-29 10:11:11.091 23332 23332 I MultiDex: Installing application
07-29 10:11:11.091 23332 23332 I MultiDex: VM has multidex support, MultiDex support library is disabled.
07-29 10:11:11.136 23332 23332 I FirebaseInitProvider: FirebaseApp initialization successful
07-29 10:11:11.640 23332 23332 W tor.riotx.debu: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
07-29 10:11:12.244 23332 23332 W tor.riotx.debu: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (light greylist, reflection)
07-29 10:11:12.244 23332 23332 W tor.riotx.debu: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (light greylist, reflection)
07-29 10:11:12.245 23332 23332 W tor.riotx.debu: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
07-29 10:11:12.245 23332 23332 W tor.riotx.debu: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
07-29 10:11:12.284 23332 23332 W tor.riotx.debu: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
07-29 10:11:12.284 23332 23332 W tor.riotx.debu: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
07-29 10:11:12.284 23332 23332 W tor.riotx.debu: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
07-29 10:11:12.286 23332 23332 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
07-29 10:11:12.323 23332 23332 V VectorApplication: ----------------------------------------------------------------
07-29 10:11:12.324 23332 23332 V VectorApplication: ----------------------------------------------------------------
07-29 10:11:12.324 23332 23359 I stetho  : Listening on @stetho_im.vector.riotx.debug_devtools_remote
07-29 10:11:12.325 23332 23332 V VectorApplication:  Application version: 0.21.0-dev [205129092] (G-b2661)
07-29 10:11:12.327 23332 23332 V VectorApplication:  SDK version: 0.0.1 (f47bef71)
07-29 10:11:12.328 23332 23332 V VectorApplication:  Local time: 07-29 10:11:12.316+0100
07-29 10:11:12.330 23332 23332 V VectorApplication: ----------------------------------------------------------------
07-29 10:11:12.332 23332 23332 V VectorApplication: ----------------------------------------------------------------
07-29 10:11:12.332 23332 23332 V VectorApplication: 
07-29 10:11:12.332 23332 23332 V VectorApplication: 
07-29 10:11:12.332 23332 23332 V VectorApplication: 
07-29 10:11:12.427 23332 23362 W tor.riotx.debu: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (light greylist, reflection)
07-29 10:11:12.427 23332 23362 W tor.riotx.debu: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (light greylist, reflection)
07-29 10:11:12.428 23332 23362 W tor.riotx.debu: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (light greylist, reflection)
07-29 10:11:12.428 23332 23362 W tor.riotx.debu: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (light greylist, reflection)
07-29 10:11:12.428 23332 23362 W tor.riotx.debu: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (light greylist, reflection)
07-29 10:11:12.429 23332 23362 W tor.riotx.debu: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (light greylist, reflection)
07-29 10:11:12.738 23332 23332 I RealmKeysUtils: Found key for alias:session_db_89a7d7e823ed9d30279614b5df300967
07-29 10:11:13.255 23332 23332 V SessionRealmConfigurationFactory: Successfully create realm instance
07-29 10:11:13.296 23332 23332 I RealmKeysUtils: Found key for alias:crypto_module_89a7d7e823ed9d30279614b5df300967
07-29 10:11:15.394 23332 23332 D AndroidRuntime: Shutting down VM
07-29 10:11:15.418 23332 23332 E AndroidRuntime: FATAL EXCEPTION: main
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Process: im.vector.riotx.debug, PID: 23332
07-29 10:11:15.418 23332 23332 E AndroidRuntime: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm': Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform> Path:Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform>. (Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform> Path: /data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform>) (/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7050)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm': Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform> Path:Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform>. (Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform> Path: /data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm
07-29 10:11:15.418 23332 23332 E AndroidRuntime: Exception backtrace:
07-29 10:11:15.418 23332 23332 E AndroidRuntime: <backtrace not supported on this platform>) (/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at io.realm.Realm.getInstance(Realm.java:428)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:61)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:129)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.newInstance(RealmCryptoStore_Factory.java:43)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:31)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:10)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:185)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:34)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-29 10:11:15.418 23332 23332 E AndroidRuntime:        at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.room.DefaultEventRelationsAggregationTask_Factory.get(DefaultEventRelationsAggregationTask_Factory.java:26)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.room.DefaultEventRelationsAggregationTask_Factory.get(DefaultEventRelationsAggregationTask_Factory.java:9)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.room.EventRelationsAggregationUpdater_Factory.get(EventRelationsAggregationUpdater_Factory.java:29)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.room.EventRelationsAggregationUpdater_Factory.get(EventRelationsAggregationUpdater_Factory.java:8)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at dagger.internal.SetFactory.get(SetFactory.java:126)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at dagger.internal.SetFactory.get(SetFactory.java:37)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:187)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:43)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1376)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.SessionManager.getOrCreateSession(SessionManager.kt:42)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.matrix.android.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:85)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at im.vector.riotx.VectorApplication.onCreate(VectorApplication.kt:122)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
07-29 10:11:15.421 23332 23332 E AndroidRuntime:        ... 8 more
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: Uncaught exception: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm': Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: <backtrace not supported on this platform> Path:Exception backtrace:
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: <backtrace not supported on this platform>. (Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: <backtrace not supported on this platform> Path: /data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.422 23332 23332 V VectorUncaughtExceptionHandler: <backtrace not supported on this platform>) (/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: FATAL EXCEPTION RiotX Build : 205129092
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: RiotX Version : 0.21.0-dev [205129092] (G-b2661)
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: SDK Version : 0.0.1 (f47bef71)
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: Phone : SM-G950F (G950FXXS9DTEA 9 REL)
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: Memory statuses 
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: usedSize   1 MB
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: freeSize   1 MB
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: totalSize   3 MB
07-29 10:11:15.467 23332 23332 E VectorUncaughtExceptionHandler: Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm': Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform> Path:Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform>. (Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform> Path: /data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform>) (/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at android.os.Looper.loop(Looper.java:214)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at android.app.ActivityThread.main(ActivityThread.java:7050)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at java.lang.reflect.Method.invoke(Native Method)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm': Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform> Path:Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform>. (Invalid top array (ref: 86495112, size: 15057921)
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform> Path: /data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: Exception backtrace:
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler: <backtrace not supported on this platform>) (/data/data/im.vector.riotx.debug/files/cddcdecf723305fb75165d273b81a887/crypto_store.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
07-29 10:11:15.468 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at io.realm.Realm.getInstance(Realm.java:428)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:61)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:129)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.newInstance(RealmCryptoStore_Factory.java:43)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:31)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:10)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:185)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:34)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.room.DefaultEventRelationsAggregationTask_Factory.get(DefaultEventRelationsAggregationTask_Factory.java:26)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.room.DefaultEventRelationsAggregationTask_Factory.get(DefaultEventRelationsAggregationTask_Factory.java:9)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.room.EventRelationsAggregationUpdater_Factory.get(EventRelationsAggregationUpdater_Factory.java:29)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.room.EventRelationsAggregationUpdater_Factory.get(EventRelationsAggregationUpdater_Factory.java:8)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at dagger.internal.SetFactory.get(SetFactory.java:126)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at dagger.internal.SetFactory.get(SetFactory.java:37)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:187)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:43)
07-29 10:11:15.469 23332 23332 E VectorUncaughtExceptionHandler:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1376)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.SessionManager.getOrCreateSession(SessionManager.kt:42)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.matrix.android.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:85)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        at im.vector.riotx.VectorApplication.onCreate(VectorApplication.kt:122)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
07-29 10:11:15.470 23332 23332 E VectorUncaughtExceptionHandler:        ... 8 more
```

**Comment by BillCarsonFr** [comment]
Yeah it's the infamous corrupted  realm base issue :/
We could have some strategies to try to recover corrupted DB
Corrupted Session DB, we can just initial sync again
Crypto DB, we can clear it but you will loose all keys (but at least you don't have to logout)... you'll need probably to enter passphrase to get backup
Auth DB, no other solution than to clear all

**Comment by richvdh** [comment]
I guess this is no longer important.
