### ISSUE TITLE
error on create room

### ISSUE THREAD

**Issue by ramtinsafadoust** [vector-im/element-android#2131]
hi i forked this project but after run when i want create room:
this error happened:

can anybody help me ?

W/RetrofitExtensionsKt: The error returned by the server is not a MatrixError
E/TaskExecutor$execute: Task failed
    OtherServerError(errorBody=<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    , httpCode=404)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:101)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:59)
        at org.matrix.android.sdk.internal.network.Request.execute(Request.kt:50)
        at org.matrix.android.sdk.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.RuntimeException: HTTP 404: <html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    
    	... 10 more
V/VectorUncaughtExceptionHandler: Uncaught exception: OtherServerError(errorBody=<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    , httpCode=404)
E/VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 40100082
    Element Version : 1.0.8-dev [40100082] (F--)
    SDK Version : 0.0.1 ()
    Phone : LLD-L21 (9.1.0.161C185 9 REL)
    Memory statuses 
    usedSize   25 MB
    freeSize   2 MB
    totalSize   27 MB
    Thread: DefaultDispatcher-worker-10, Exception: OtherServerError(errorBody=<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    , httpCode=404)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:101)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:59)
        at org.matrix.android.sdk.internal.network.Request.execute(Request.kt:50)
        at org.matrix.android.sdk.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.RuntimeException: HTTP 404: <html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    
    	... 10 more
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-10
    Process: im.vector.app.debug, PID: 22566
    OtherServerError(errorBody=<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    , httpCode=404)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:101)
        at org.matrix.android.sdk.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:59)
        at org.matrix.android.sdk.internal.network.Request.execute(Request.kt:50)
        at org.matrix.android.sdk.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.RuntimeException: HTTP 404: <html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    
    	... 10 more
I/VectorBaseActivity: onPause Activity CreateDirectRoomActivity
I/Process: Sending signal. PID: 22566 SIG: 9
Process 22566 terminated.

**Comment by bmarty** [comment]
is your homeserver correctly setup?

**Comment by ramtinsafadoust** [comment]
> 
> 
> is your homeserver correctly setup?

there is no problem with GooglePlay version with my server

you can test

matrix.farmehr.com

**Comment by ramtinsafadoust** [comment]
i can start room from googleplay version to forked version
but can not start room from forked versin to googlepay versino (app will crash and in below error in my android studio debugger )

just forked without any changes

**Comment by bmarty** [comment]
Can you send a rageshake please?

**Comment by ramtinsafadoust** [comment]
rageshake popup not appear after crash
i can see error on Android studio debugger

are you test my server?

that is ok??

**Comment by ramtinsafadoust** [comment]
i try to send rage shake by shaking my phone

but got error 

the bug report faild (internal error)

**Comment by ramtinsafadoust** [comment]
nobody can help me?

im so confused

this is important for me

**Comment by ramtinsafadoust** [comment]
please some one help me
i'm go crazy

when i want create direct conversion 

android studio show this error => :


OtherServerError(errorBody=<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.14.0 (Ubuntu)</center>
    </body>
    </html>
    , httpCode=404)

**Comment by bmarty** [comment]
I have no pb using your server and create a room on it.
Please do not post too many comments :)

**Comment by bmarty** [comment]
Please re-open if you still have the problem
