### ISSUE TITLE
Issue in getLastAuthenticatedSession()

### ISSUE THREAD

**Issue by sagarjain2** [vector-im/element-android#2229]
I was integrated the old version of matrix-sdk-android (element android ver 0.18.0) 
& now I updated with matrix-sdk-android to ver 1.0.0 in my latest Android App but when I override the my new App(matrix-sdk-android to ver 1.0.0) on old App (element android ver 0.18.0) then I found below error message & due to this I can not see my old chat message data into the list

Error of getLastAuthenticatedSession()

java.lang.IllegalArgumentException: Field already exists in 'IncomingRoomKeyRequestEntity': requestBodyAlgorithm
        at io.realm.MutableRealmObjectSchema.checkFieldNameIsAvailable(MutableRealmObjectSchema.java:369)
        at io.realm.MutableRealmObjectSchema.checkNewFieldName(MutableRealmObjectSchema.java:364)
        at io.realm.MutableRealmObjectSchema.addField(MutableRealmObjectSchema.java:108)
        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrateTo2Legacy(RealmCryptoStoreMigration.kt:92)
        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrate(RealmCryptoStoreMigration.kt:64)
        at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:782)
        at io.realm.internal.OsSharedRealm.runMigrationCallback(OsSharedRealm.java:533)
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:136)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:360)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
        at io.realm.Realm.getInstance(Realm.java:428)
        at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:61)
        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:135)
        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.newInstance(RealmCryptoStore_Factory.java:43)
        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:31)
        at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:10)

**Comment by sagarjain2** [comment]
More detail
**I have upgraded the element matrix SDK (to Ver 1.0.0) into my android app. After upgrade Realm migration inside element matrix SDK throw error** 
i.e
java.lang.IllegalArgumentException: Field already exists in 'IncomingRoomKeyRequestEntity': requestBodyAlgorithm
at io.realm.MutableRealmObjectSchema.checkFieldNameIsAvailable(MutableRealmObjectSchema.java:369)
at io.realm.MutableRealmObjectSchema.checkNewFieldName(MutableRealmObjectSchema.java:364)
at io.realm.MutableRealmObjectSchema.addField(MutableRealmObjectSchema.java:108)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrateTo2Legacy(RealmCryptoStoreMigration.kt:92)
at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrate(RealmCryptoStoreMigration.kt:64)
at io.realm.BaseRealm$6.on

Thanks, and please let me how to solve this.
