### ISSUE TITLE
Start on boot not working

### ISSUE THREAD

**Issue by GammaPi** [vector-im/element-android#2419]
**Describe the bug**
I have to manually start app after reboot despite start on boot feature is selected.

**To Reproduce**
1. Select "start on boot in notification settings"
2. Reboot phone
3. Open element again
4. The app shows start screen. (I can't get any message if I don't manually start every time.)

**Expected behavior**
App start in background and start sync.

**Smartphone (please complete the following information):**
 - Device: Oneplus 8 
 - OS: Android 11

**Additional context**
 - App version and store  - F-Droid 1.0.10

**Comment by GammaPi** [comment]
Did element-android even implemented this feature?
Since the original riot-android have this class, while element-android doesn't. [Check this](https://github.com/vector-im/riot-android/blob/b07028f66c14ffd1e79ec76adc647ede5a6e3270/vector/src/main/java/im/vector/receiver/VectorBootReceiver.java).

**Comment by bmarty** [comment]
Now we have https://github.com/vector-im/element-android/blob/develop/vector/src/fdroid/java/im/vector/app/fdroid/receiver/OnApplicationUpgradeOrRebootReceiver.kt#L28

We will do some test

**Comment by notramo** [comment]
I noticed multiple times that Android said Element crashed while there wasn't an open window. Maybe the background service crashed?

**Comment by onurays** [comment]
```
    Thread: main, Exception: java.lang.RuntimeException: Unable to instantiate receiver im.vector.app.fdroid.receiver.OnApplicationUpgradeOrRebootReceiver: java.lang.ClassNotFoundException: Didn't find class "im.vector.app.fdroid.receiver.OnApplicationUpgradeOrRebootReceiver" on path: DexPathList[[zip file "/data/app/~~eECUNm0RzYqawXL9lj0dpg==/de.bwi.bwmessenger.debug-eNpHfQGeSMPJXPg26GPHPQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~eECUNm0RzYqawXL9lj0dpg==/de.bwi.bwmessenger.debug-eNpHfQGeSMPJXPg26GPHPQ==/lib/x86, /data/app/~~eECUNm0RzYqawXL9lj0dpg==/de.bwi.bwmessenger.debug-eNpHfQGeSMPJXPg26GPHPQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3920)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1896)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "im.vector.app.fdroid.receiver.OnApplicationUpgradeOrRebootReceiver" on path: DexPathList[[zip file "/data/app/~~eECUNm0RzYqawXL9lj0dpg==/de.bwi.bwmessenger.debug-eNpHfQGeSMPJXPg26GPHPQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~eECUNm0RzYqawXL9lj0dpg==/de.bwi.bwmessenger.debug-eNpHfQGeSMPJXPg26GPHPQ==/lib/x86, /data/app/~~eECUNm0RzYqawXL9lj0dpg==/de.bwi.bwmessenger.debug-eNpHfQGeSMPJXPg26GPHPQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:202)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
        at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3913)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1896) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7464) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955) 
```

**Comment by bagvand** [comment]
Issue will happen when obfuscate = true.
