### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Alvazz** [vector-im/element-android#2464]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S6]
 - OS: [e.g. Android 6.0]

**Additional context**
 - App version and store [e.g. 1.0.0 - F-Droid]
 - Homeserver: [e.g. matrix.org]

11/28 04:02:07: Launching 'vector' on Pixel 4 XL API 29.
Install successfully finished in 2 s 620 ms.
$ adb shell am start -n "im.vector.app.debug/im.vector.app.features.Alias" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 1319 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: Installing application
    VM has multidex support, MultiDex support library is disabled.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: im.vector.app.debug, PID: 1319
    java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app.debug/files/matrix-sdk-auth.realm': Realm file decryption failed Path:Exception backtrace:
    <backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/im.vector.app.debug/files/matrix-sdk-auth.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/im.vector.app.debug/files/matrix-sdk-auth.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app.debug/files/matrix-sdk-auth.realm': Realm file decryption failed Path:Exception backtrace:
    <backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/im.vector.app.debug/files/matrix-sdk-auth.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/im.vector.app.debug/files/matrix-sdk-auth.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:172)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:248)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getInstance(Realm.java:424)
        at org.matrix.android.sdk.internal.auth.db.RealmPendingSessionStore.getPendingSessionData(RealmPendingSessionStore.kt:45)
        at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.<init>(DefaultAuthenticationService.kt:74)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent.defaultAuthenticationService(DaggerMatrixComponent.java:161)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent.injectMatrix(DaggerMatrixComponent.java:305)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent.inject(DaggerMatrixComponent.java:300)
        at org.matrix.android.sdk.api.Matrix.<init>(Matrix.kt:53)
        at org.matrix.android.sdk.api.Matrix.<init>(Matrix.kt:41)
        at org.matrix.android.sdk.api.Matrix$Companion.getInstance(Matrix.kt:88)
        at im.vector.app.core.di.VectorModule$Companion.providesMatrix(VectorModule.kt:61)
        at im.vector.app.core.di.VectorModule.providesMatrix(Unknown Source:2)
        at im.vector.app.core.di.VectorModule_ProvidesMatrixFactory.providesMatrix(VectorModule_ProvidesMatrixFactory.java:31)
        at im.vector.app.core.di.DaggerVectorComponent.matrix(DaggerVectorComponent.java:395)
        at im.vector.app.core.di.DaggerVectorComponent.legacySessionImporter(DaggerVectorComponent.java:263)
        at im.vector.app.core.di.DaggerVectorComponent.injectVectorApplication(DaggerVectorComponent.java:611)
        at im.vector.app.core.di.DaggerVectorComponent.inject(DaggerVectorComponent.java:390)
        at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:114)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        	... 8 more
I/Process: Sending signal. PID: 1319 SIG: 9

**Comment by bmarty** [comment]
version of the app?

**Comment by miterion** [comment]
> version of the app?

I have the same problem with version 1.0.11 installed from the beta channel in the Google Play Store.

**Comment by miterion** [comment]
Here is the full description:

**Describe the bug**
The app crashes immediately on start-up.

**To Reproduce**
Steps to reproduce the behavior:
1. Launch the app

**Expected behavior**
The app starts and becomes interactive.

**Screenshots**
 Except from a brief green startup screen with the element logo nothing much can be seen.

**Smartphone (please complete the following information):**
 - Device: Oneplus 3t
 - OS: Android 9

**Additional context**
 - App version and store: 1.0.11 - Google Play Beta Channel
 - Homeserver: d120.de

The backtrace is similiar to the one @Alvazz posted.

**Comment by faenil** [comment]
similar crash here on 
Sony XZ2
OS: Android 10

Element v1.0.11 as released on Google Play

The issue started right after upgrading to 1.0.11, the app is now unusable

**Comment by miterion** [comment]
I could get it to work by using androids „Clear storage“ functionality.
