### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by browep** [vector-im/element-android#2499]
**Describe the bug**
App crashes on launch

**To Reproduce**
1. login to account
2. use app for awhile

**Expected behavior**
app open

**Actual Behavior**
app crashes

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 11

**Additional context**

* v1.0.11 - Play Store
* custom homeserver

there about 6GB of free space on the device

stacktrace from ADB
```
2020-12-07 15:30:49.799 25220-25220/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: im.vector.app, PID: 25220
    java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm': Realm file decryption failed Path:Exception backtrace:
    <backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm': Realm file decryption failed Path:Exception backtrace:
    <backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:6)
        at io.realm.BaseRealm.<init>(BaseRealm.java:26)
        at io.realm.Realm.<init>(Realm.java:8)
        at io.realm.Realm.getInstance(Realm.java:23)
        at org.matrix.android.sdk.api.MatrixCallback$DefaultImpls.doRealmTransaction(MatrixCallback.kt:1)
        at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:8)
        at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:2)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
        at org.matrix.android.sdk.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
        at org.matrix.android.sdk.internal.crypto.algorithms.olm.MXOlmDecryptionFactory_Factory.get(MXOlmDecryptionFactory_Factory.java:1)
        at org.matrix.android.sdk.internal.crypto.RoomDecryptorProvider_Factory.get(RoomDecryptorProvider_Factory.java:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
        at org.matrix.android.sdk.internal.crypto.EventDecryptor_Factory.get(EventDecryptor_Factory.java:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
        at org.matrix.android.sdk.internal.crypto.verification.VerificationMessageProcessor_Factory.get(VerificationMessageProcessor_Factory.java:1)
        at dagger.internal.SetFactory.get(SetFactory.java:10)
        at org.matrix.android.sdk.internal.database.EventInsertLiveObserver_Factory.get(EventInsertLiveObserver_Factory.java:1)
        at dagger.internal.SetFactory.get(SetFactory.java:10)
        at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
        at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:1)
2020-12-07 15:30:49.799 25220-25220/? E/AndroidRuntime:     at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:4)
        at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:99)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        	... 8 more
```

**Comment by notramo** [comment]
I can confirm it on LineageOS 16 and 17 (Android 9 and 10).

**Comment by seasoned-code** [comment]
Confirming as well G7 ThinQ Android 9. However, it just crashes and prevents app from opening.

**Comment by faaaaabi** [comment]
I can also confirm that for Android 10 on Honor Device. It crashes on startup

**Comment by motey** [comment]
Confirmed on Pixel 4XL Android 12
Same error:
`<backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/25bc53540da2dae23fb9d3d64f6cf84f/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.`

Cleared App cache, rebooted phone; element still crashing on startup
