### ISSUE TITLE
RealmMigrationNeededException on fresh install

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#272]
```
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: Uncaught exception: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.userId' has been added.
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.deviceId' has been added.
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.olmAccountData' has been added.
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.deviceSyncToken' has been added.
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.globalBlacklistUnverifiedDevices' has been added.
07-02 17:49:11.503  2796  2796 V VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.backupVersion' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: FATAL EXCEPTION RiotX Build : 156208286
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: RiotX Version : 0.1.0 (G-156d88e7-2019-07-02 17:54:22 +0200)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: SDK Version : 0.0.1 (156d88e7)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: Phone : SM-G920F (G920FXXU6ERF5 7.0 REL)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: Memory statuses 
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: usedSize   12 MB
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: freeSize   6 MB
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: totalSize   19 MB
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.userId' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.deviceId' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.olmAccountData' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.deviceSyncToken' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.globalBlacklistUnverifiedDevices' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.backupVersion' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:154)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.userId' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.deviceId' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.olmAccountData' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.deviceSyncToken' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.globalBlacklistUnverifiedDevices' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: - Property 'CryptoMetadataEntity.backupVersion' has been added.
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.BaseRealm.<init>(BaseRealm.java:135)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.BaseRealm.<init>(BaseRealm.java:103)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.Realm.<init>(Realm.java:163)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.Realm.createInstance(Realm.java:499)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at io.realm.Realm.getInstance(Realm.java:428)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmQueryAndCopy(Helper.kt:45)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.getAccount(RealmCryptoStore.kt:160)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.MXOlmDevice.<init>(MXOlmDevice.kt:96)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:17)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:8)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.MyDeviceInfoHolder_Factory.get(MyDeviceInfoHolder_Factory.java:25)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.MyDeviceInfoHolder_Factory.get(MyDeviceInfoHolder_Factory.java:9)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.CryptoManager_Factory.get(CryptoManager_Factory.java:145)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.crypto.CryptoManager_Factory.get(CryptoManager_Factory.java:27)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.room.timeline.SimpleTimelineEventFactory_Factory.get(SimpleTimelineEventFactory_Factory.java:28)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.room.timeline.SimpleTimelineEventFactory_Factory.get(SimpleTimelineEventFactory_Factory.java:10)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.database.mapper.RoomSummaryMapper_Factory.get(RoomSummaryMapper_Factory.java:22)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.database.mapper.RoomSummaryMapper_Factory.get(RoomSummaryMapper_Factory.java:9)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.room.DefaultRoomService_Factory.get(DefaultRoomService_Factory.java:35)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.room.DefaultRoomService_Factory.get(DefaultRoomService_Factory.java:11)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.notification.DefaultProcessEventForPushTask_Factory.get(DefaultProcessEventForPushTask_Factory.java:26)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.notification.DefaultProcessEventForPushTask_Factory.get(DefaultProcessEventForPushTask_Factory.java:9)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.notification.BingRuleWatcher_Factory.get(BingRuleWatcher_Factory.java:39)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.notification.BingRuleWatcher_Factory.get(BingRuleWatcher_Factory.java:11)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at dagger.internal.SetFactory.get(SetFactory.java:126)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at dagger.internal.SetFactory.get(SetFactory.java:37)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:98)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:25)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:772)
07-02 17:49:11.505  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.SessionManager.getOrCreateSession(SessionManager.kt:40)
07-02 17:49:11.506  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.matrix.android.internal.auth.DefaultAuthenticator.getLastAuthenticatedSession(DefaultAuthenticator.kt:57)
07-02 17:49:11.506  2796  2796 E VectorUncaughtExceptionHandler: 	at im.vector.riotx.VectorApplication.onCreate(VectorApplication.kt:107)
07-02 17:49:11.506  2796  2796 E VectorUncaughtExceptionHandler: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
07-02 17:49:11.506  2796  2796 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
07-02 17:49:11.506  2796  2796 E VectorUncaughtExceptionHandler: 	... 8 more
07-02 17:49:11.512  2796  2796 E AndroidRuntime: FATAL EXCEPTION: main
07-02 17:49:11.512  2796  2796 E AndroidRuntime: Process: im.vector.riotx, PID: 2796
07-02 17:49:11.512  2796  2796 E AndroidRuntime: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.userId' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.deviceId' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.olmAccountData' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.deviceSyncToken' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.globalBlacklistUnverifiedDevices' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.backupVersion' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.userId' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.deviceId' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.olmAccountData' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.deviceSyncToken' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.globalBlacklistUnverifiedDevices' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: - Property 'CryptoMetadataEntity.backupVersion' has been added.
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:135)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:103)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.Realm.<init>(Realm.java:163)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.Realm.createInstance(Realm.java:499)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:428)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmQueryAndCopy(Helper.kt:45)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.getAccount(RealmCryptoStore.kt:160)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.MXOlmDevice.<init>(MXOlmDevice.kt:96)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:17)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:8)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.MyDeviceInfoHolder_Factory.get(MyDeviceInfoHolder_Factory.java:25)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.MyDeviceInfoHolder_Factory.get(MyDeviceInfoHolder_Factory.java:9)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.CryptoManager_Factory.get(CryptoManager_Factory.java:145)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.CryptoManager_Factory.get(CryptoManager_Factory.java:27)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.room.timeline.SimpleTimelineEventFactory_Factory.get(SimpleTimelineEventFactory_Factory.java:28)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.room.timeline.SimpleTimelineEventFactory_Factory.get(SimpleTimelineEventFactory_Factory.java:10)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.database.mapper.RoomSummaryMapper_Factory.get(RoomSummaryMapper_Factory.java:22)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.database.mapper.RoomSummaryMapper_Factory.get(RoomSummaryMapper_Factory.java:9)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.room.DefaultRoomService_Factory.get(DefaultRoomService_Factory.java:35)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.room.DefaultRoomService_Factory.get(DefaultRoomService_Factory.java:11)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.notification.DefaultProcessEventForPushTask_Factory.get(DefaultProcessEventForPushTask_Factory.java:26)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.notification.DefaultProcessEventForPushTask_Factory.get(DefaultProcessEventForPushTask_Factory.java:9)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.notification.BingRuleWatcher_Factory.get(BingRuleWatcher_Factory.java:39)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.notification.BingRuleWatcher_Factory.get(BingRuleWatcher_Factory.java:11)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at dagger.internal.SetFactory.get(SetFactory.java:126)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at dagger.internal.SetFactory.get(SetFactory.java:37)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:98)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:25)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:772)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.SessionManager.getOrCreateSession(SessionManager.kt:40)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.matrix.android.internal.auth.DefaultAuthenticator.getLastAuthenticatedSession(DefaultAuthenticator.kt:57)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at im.vector.riotx.VectorApplication.onCreate(VectorApplication.kt:107)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
07-02 17:49:11.512  2796  2796 E AndroidRuntime: 	... 8 more

**Comment by bmarty** [comment]
I think we can close this old issue now, AFAIK it has not happen recently
