### ISSUE TITLE
Rageshake /  You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#274]
Seem to appear (mainly?) when coming back from RoomDetailActivity

It's a random crash we are experimenting from time to time

```
The specified child already has a parent. You must call removeView() on the child's parent first.
at android.view.ViewGroup.addViewInner(ViewGroup.java:4656)
at android.view.ViewGroup.addView(ViewGroup.java:4497)
at android.view.ViewGroup.addView(ViewGroup.java:4437)
at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:857)
at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8470)
at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8428)
at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8416)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1572)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3983)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3747)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1898)
at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:412)
```

https://github.com/matrix-org/riot-android-rageshakes/issues/5859
https://github.com/matrix-org/riot-android-rageshakes/issues/5854
https://github.com/matrix-org/riot-android-rageshakes/issues/5853

**Comment by bmarty** [comment]
Seems to appear less often, but keep it open for now.
Maybe due to the fact that we do not display the KeysBackup banner when uploading keys.

**Comment by ouchadam** [comment]
filtering by latest version in the rage shakes and play console, can't see any instances of this, going to close
