### ISSUE TITLE
Sending an image from the gallery crashes Element

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-android#3119]
#### Describe the bug

Sending an image from a gallery into a room crashes Element.

#### To Reproduce
1. Open a room
2. Click `+` in lower left.
3. Select "Gallery".
4. Select an image.
5. A crash happens.

#### Expected behavior
Element should send the image to the room successfully.

#### details.log.gz

This is rageshake 2021-04-05/090607.

```


--------------------------------- crash call stack ---------------------------------
Element Build : 40101032
Element Version : 1.1.3 [40101032] (G-b1729)
SDK Version : 0.0.1 (a6c43f46)
Phone : MI 3W (V11.0.8.0.QFQEUXM 10 REL)
Memory statuses 
usedSize   38 MB
freeSize   3 MB
totalSize   41 MB
Thread: main, Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	... 1 more
Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1689)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1189)
	at im.vector.lib.multipicker.utils.ImageUtils.getOrientation(ImageUtils.kt:1)
	at im.vector.lib.multipicker.ImagePicker.getSelectedFiles(ImagePicker.kt:12)
	at im.vector.app.features.attachments.AttachmentsHelper.onImageResult(AttachmentsHelper.kt:3)
	at im.vector.app.features.home.room.detail.RoomDetailFragment$attachmentImageActivityResultLauncher$1.invoke(RoomDetailFragment.kt:4)
	at im.vector.app.features.home.room.detail.RoomDetailFragment$attachmentImageActivityResultLauncher$1.invoke(RoomDetailFragment.kt:5)
	at im.vector.app.core.extensions.FragmentKt$sam$androidx_activity_result_ActivityResultCallback$0.onActivityResult(Unknown Source:2)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:12)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:3)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:11)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:72)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:22)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7833)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3295)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	... 3 more


Number of logs: 17
Application: riot-android
Labels: 1.1.3, GooglePlay, master, [Element], crash
User-Agent: Element/1.1.3 (Linux; U; Android 10; MI 3W Build/QKQ1.190910.00; Flavour GooglePlay; MatrixAndroidSDK_X 0.0.1)
Version: 1.1.3 [40101032] (G-a6c43f46-2021-03-18 10:36:22 +0100)
app_language: en_GB
branch_name: master
build_number: 1729
default_app_language: en_GB
device: MI 3W
device_id: HAJUETHHIX
locale: en_GB
matrix_sdk_version: 0.0.1 (a6c43f46)
multi_window: OFF
olm_version: 3.2.2 - olm version (3.2.2) - 3745ea5-2021-02-22 17:06:13 -0500
os: 10 (API 29) V11.0.8.0.QFQEUXM-REL
server_version: undefined
theme: dark
user_id: @dkasak:termina.org.uk
verbose_log: ON

**Comment by bahur142** [comment]
This is old problem described here - https://github.com/vector-im/element-android/issues/2274
And probably the most affected are old xiaomi devices. Mine mi4 is affected, but the others mi6 and mi8 not.

**Comment by dkasak** [comment]
Perhaps, but not only Xiaomi devices are affected. The reason I even started investigating is that a friend had a crash occur when sending an image from the gallery. He doesn't have a Xiaomi but a Blackview BV9100. Unfortunately he didn't rageshake his crash so I decided to test instead and the crash happened in the same conditions for me.

**Comment by hieronymousch** [comment]
Can confirm this for Blackview 9800 as well
