### ISSUE TITLE
Crash with `rxSingle`

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#3180]
Fails fast feature must be on to see this problem. To reproduce: try to create a DM and type some chars in the search user field, in order to cancel a request.

```
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Cancelled(throwable=kotlinx.coroutines.JobCancellationException: RxSingleCoroutine was cancelled; job=RxSingleCoroutine{Cancelling}@8b85a04)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:9)
        at io.reactivex.plugins.RxJavaPlugins.handleUndeliverableException(RxJavaPlugins.java:2)
        at kotlinx.coroutines.rx2.RxSingleCoroutine.onCancelled(RxSingle.kt:3)
        at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:2)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:17)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:27)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:2)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:2)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:14)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
     Caused by: Cancelled(throwable=kotlinx.coroutines.JobCancellationException: RxSingleCoroutine was cancelled; job=RxSingleCoroutine{Cancelling}@8b85a04)
        at org.matrix.android.sdk.internal.session.user.model.DefaultSearchUserTask.execute(SearchUserTask.kt:36)
        at org.matrix.android.sdk.internal.session.user.model.DefaultSearchUserTask$execute$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:14) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10) 
     Caused by: kotlinx.coroutines.JobCancellationException: RxSingleCoroutine was cancelled; job=RxSingleCoroutine{Cancelling}@8b85a04
```

**Comment by bmarty** [comment]
We should not wrap the CancellationException into Failure.Cancelled because this code will not work:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/3940906/115434049-86cdbb80-a208-11eb-8acf-9f57ab10ba62.png">
