### ISSUE TITLE
Crash on launch with RealmMigrationNeededException

### ISSUE THREAD

**Issue by akhilvarkey** [vector-im/element-android#3335]
#### Describe the bug
Crash on launch. See stack trace at the end.

#### To Reproduce
1. Click to launch Application
2. Application Crashes with Fatal Exception on launch

#### Expected behavior
Application launching and working as expected.

#### Additional context
 - App version and store: F-Droid universal debug apk produced as build artifact of build [2288](https://buildkite.com/matrix-dot-org/element-android/builds/2288) and onwards.
 - Homeserver:matrix.org

Stack Trace:
```
FATAL EXCEPTION: main
Process: im.vector.app.debug, PID: 14050
java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'SpaceChildSummaryEntity.suggested' has been added.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'SpaceChildSummaryEntity.suggested' has been added.
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
	at io.realm.BaseRealm.<init>(BaseRealm.java:141)
	at io.realm.BaseRealm.<init>(BaseRealm.java:108)
	at io.realm.Realm.<init>(Realm.java:159)
	at io.realm.Realm.createInstance(Realm.java:495)
	at io.realm.RealmCache.createInstance(RealmCache.java:481)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
	at io.realm.Realm.getInstance(Realm.java:424)
	at org.matrix.android.sdk.internal.database.SessionRealmConfigurationFactory.create(SessionRealmConfigurationFactory.kt:79)
	at org.matrix.android.sdk.internal.session.SessionModule$Companion.providesRealmConfiguration(SessionModule.kt:189)
	at org.matrix.android.sdk.internal.session.SessionModule.providesRealmConfiguration(Unknown Source:2)
	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(SessionModule_ProvidesRealmConfigurationFactory.java:36)
	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:26)
	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:237)
	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:54)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:2060)
	at org.matrix.android.sdk.internal.SessionManager.getOrCreateSession(SessionManager.kt:42)
	at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:75)
	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:164)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
```
Please take a look at this @bmarty

**Comment by akhilvarkey** [comment]
Thank you @bmarty
