### ISSUE TITLE
Element crashes whenever I want to open a chat (becomes 100% unusable)

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/element-android#3864]
Whenever I select a chat room from the home screen, the chat is not opened and Element crashes instead. Clearing the cache didn't help, clearing the app data and logging back in didn't help. I have sent several crash reports.

Element Android: 1.2.0 [40102001] (Gb3043)
Matrix-SDK-Version: 0.0.1 (4f6b6ddf)
OLM-Version: 3.2.4
Android-Version: 5.1.1 (I know it's old)
Installed via: Play Store
GApps installed: Yes

**Comment by MazeChaZer** [comment]
This is the stack trace that logcat gives me, looks like it should help narrow down the issue:

```
E/AndroidRuntime( 8297): FATAL EXCEPTION: main
E/AndroidRuntime( 8297): Process: im.vector.app, PID: 8297
E/AndroidRuntime( 8297): java.lang.RuntimeException: Unable to start activity ComponentInfo{im.vector.app/im.vector.app.features.home.room.detail.RoomDetailActivity}: android.view.InflateException: Binary XML file line #187: Error inflating class im.vector.app.features.home.room.detail.composer.VoiceMessageRecorderView
E/AndroidRuntime( 8297):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime( 8297):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime( 8297):        at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 8297):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 8297):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8297):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8297):        at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime( 8297):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8297):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8297):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 8297):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 8297): Caused by: android.view.InflateException: Binary XML file line #187: Error inflating class im.vector.app.features.home.room.detail.composer.VoiceMessageRecorderView
E/AndroidRuntime( 8297):        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime( 8297):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/AndroidRuntime( 8297):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 8297):        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 8297):        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 8297):        at im.vector.app.features.home.room.detail.RoomDetailFragment.getBinding(RoomDetailFragment.kt:1)
E/AndroidRuntime( 8297):        at im.vector.app.features.home.room.detail.RoomDetailFragment.getBinding(RoomDetailFragment.kt:31)
E/AndroidRuntime( 8297):        at im.vector.app.core.platform.VectorBaseFragment.onCreateView(VectorBaseFragment.kt:3)
E/AndroidRuntime( 8297):        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:16)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:27)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
E/AndroidRuntime( 8297):        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
E/AndroidRuntime( 8297):        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
E/AndroidRuntime( 8297):        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
E/AndroidRuntime( 8297):        at android.app.Activity.performStart(Activity.java:6006)
E/AndroidRuntime( 8297):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
E/AndroidRuntime( 8297):        ... 10 more
E/AndroidRuntime( 8297): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8297):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 8297):        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 8297):        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime( 8297):        ... 29 more
E/AndroidRuntime( 8297): Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.ImageButton im.vector.app.databinding.ViewVoiceMessageRecorderBinding.voiceMessageMicButton' on a null object reference
E/AndroidRuntime( 8297):        at im.vector.app.features.home.room.detail.composer.VoiceMessageRecorderView.onVisibilityChanged(VoiceMessageRecorderView.kt:4)
E/AndroidRuntime( 8297):        at android.view.View.dispatchVisibilityChanged(View.java:8740)
E/AndroidRuntime( 8297):        at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1148)
E/AndroidRuntime( 8297):        at android.view.View.setFlags(View.java:9783)
E/AndroidRuntime( 8297):        at android.view.View.<init>(View.java:4168)
E/AndroidRuntime( 8297):        at android.view.ViewGroup.<init>(ViewGroup.java:498)
E/AndroidRuntime( 8297):        at android.view.ViewGroup.<init>(ViewGroup.java:494)
E/AndroidRuntime( 8297):        at androidx.constraintlayout.widget.ConstraintLayout.<init>(ConstraintLayout.java:51)
E/AndroidRuntime( 8297):        at im.vector.app.features.home.room.detail.composer.VoiceMessageRecorderView.<init>(VoiceMessageRecorderView.kt:2)
E/AndroidRuntime( 8297):        at im.vector.app.features.home.room.detail.composer.VoiceM
W/ActivityManager(  811):   Force finishing activity 1 im.vector.app/.features.home.room.detail.RoomDetailActivity
W/ActivityManager(  811):   Force finishing activity 2 im.vector.app/.features.home.HomeActivity
```

**Comment by MazeChaZer** [comment]
Duplicate of #3897, closing
