### ISSUE TITLE
Element keeps stopping (immediately on every attempted start)

### ISSUE THREAD

**Issue by 2011** [vector-im/element-android#3879]
#### Describe the bug

App won't start (keeps crashing immediately every time).

#### To Reproduce

Every time I try to start element (after the first) I get "Element keeps stopping" with the three usual menu items below that (I have blocked dogbin in my hosts file to prevent uploads of personal information to the interent).

#### Expected behavior

Expect app to start, of course. Had worked before for several months. Suddenly will no longer run.

#### Smartphone (please complete the following information):

Mi A3 with Android 10 (custom ROM).

#### Additional context

Element 1.2.0 from F-Droid using matrix.org

Would like (if told to delete all data, which I suspect will happen) some way of reading past messages after a recovery (not a total disaster if I have lost them, but a huge annoyance).

**Comment by 2011** [comment]
Now using Element 1.3.9. Still can not get it to open (crashes immediately when started). I have had this problem for more than four months now.

**Comment by 2011** [comment]
Now using Element 1.4.0. Still can not get it to open (crashes immediately when started). I have had this problem for six months now (completely unable to use Element).

**Comment by Tynach** [comment]
Same here with an LG V20, stock ROM (not custom). Android 8.0.0.

**Comment by ItsRogueRen** [comment]
I'm having this happen on the latest google play version and latest github release as of Mar 23 2023.

App opens, I log in, rooms load, crashes, crashes as soon as it opens from then on.

Desktop clients are completely fine.

**Comment by 2011** [comment]
Now on 1.5.28. Unable to start element for 18 months now!

The current crash log:

```
[04-04 08:31:32.517 11360:11360 E/JitsiMeetSDK]
FATAL EXCEPTION Element Build : 40105280
Element Version : 1.5.28 [40105280] (F-7ce1842f-2023-03-08 17:30:55 +0100)
SDK Version : 1.5.28 (7ce1842f)
Phone : Mi A3 (eng.golbin.20201222.080134 10 REL)
Memory statuses 
usedSize   8 MB
freeSize   503 MB
totalSize   512 MB
Thread: main, Exception: java.lang.RuntimeException: Unable to resume activity {im.vector.app/im.vector.application.features.Alias}: javax.crypto.AEADBadTagException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: javax.crypto.AEADBadTagException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.decryptBytesM(SecretStoringUtils.kt:53)
        at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.loadSecureSecretBytes(SecretStoringUtils.kt:25)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.getRealmEncryptionKey(RealmKeysUtils.kt:55)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.configureEncryption(RealmKeysUtils.kt:6)
        at org.matrix.android.sdk.internal.crypto.crosssigning.CrossSigningOlm_Factory.get(CrossSigningOlm_Factory.java:201)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:14)
        at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:50)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:14)
        at dagger.internal.DelegateFactory.get(DelegateFactory.java:5)
        at org.matrix.android.sdk.internal.session.DaggerSessionComponent$SessionComponentImpl.session(DaggerSessionComponent.java:3)
        at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:15)
        at im.vector.app.core.di.SessionInitializer.tryInitialize(SessionInitializer.kt:107)
        at im.vector.app.core.di.SessionInitializer$tryInitialize$1.invokeSuspend(SessionInitializer.kt:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:154)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:110)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:3)
        at im.vector.app.core.di.ActiveSessionHolder.getSafeActiveSession(ActiveSessionHolder.kt:7)
        at im.vector.app.push.fcm.FdroidFcmHelper.onEnterForeground(FdroidFcmHelper.kt:1)
        at im.vector.app.VectorApplication$onCreate$2.onResume(VectorApplication.kt:30)
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:35)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:20)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:293)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:52)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
        at androidx.lifecycle.ProcessLifecycleOwner.activityResumed(ProcessLifecycleOwner.java:17)
        at androidx.lifecycle.ProcessLifecycleOwner$3$1.onActivityPostResumed(ProcessLifecycleOwne
 ```

**Comment by 6ixfalls** [comment]
Seem to be experiencing the same issue. Using gitter.im, app immediately crashes after attempting to login (even after clearing all app storage). Stock android 13, Pixel 6a.

**Comment by 2011** [comment]
> Edit: Seems to be an issue with VPNs? Disabled Tailscale VPN and works fine now.

The problem I have has no relationship with VPN use (behaves the same with VPNs either enabled or disabled).

**Comment by 2011** [comment]
Just updating this in case someone ever decides to take a look at it (now on Android 11 and Element 1.6.5).

```
[09-18 16:54:14.469 1113:2422 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=im.vector.app/im.vector.application.features.Alias bnds=[428,474][562,708]} from uid 1000

[09-18 16:54:14.504 1113:1288 I/ActivityManager]
Start proc 7150:im.vector.app/u0a290 for pre-top-activity {im.vector.app/im.vector.application.features.Alias}

[09-18 16:54:14.528 7150:7150 E/im.vector.app]
Not starting debugger since process cannot load the jdwp agent.

[09-18 16:54:14.614 7150:7150 V/fb-UnpackingSoSource]
locked dso store /data/user/0/im.vector.app/lib-main

[09-18 16:54:14.616 7150:7150 I/fb-UnpackingSoSource]
dso store is up-to-date: /data/user/0/im.vector.app/lib-main

[09-18 16:54:14.616 7150:7150 V/fb-UnpackingSoSource]
releasing dso store lock for /data/user/0/im.vector.app/lib-main

[09-18 16:54:14.688 7150:7150 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: im.vector.app, PID: 7150
java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: javax.crypto.AEADBadTagException
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: javax.crypto.AEADBadTagException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.decryptBytesM(SecretStoringUtils.kt:38)
        at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.loadSecureSecretBytes(SecretStoringUtils.kt:25)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.extractKeyForDatabase(RealmKeysUtils.kt:34)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.getRealmEncryptionKey(RealmKeysUtils.kt:26)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.configureEncryption(RealmKeysUtils.kt:11)
        at org.matrix.android.sdk.internal.auth.AuthModule$Companion.providesRealmConfiguration(AuthModule.kt:52)
        at org.matrix.android.sdk.internal.auth.AuthModule.providesRealmConfiguration(AuthModule.kt:3)
        at org.matrix.android.sdk.internal.auth.AuthModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(AuthModule_ProvidesRealmConfigurationFactory.java:1)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.authDatabaseRealmConfiguration(DaggerMatrixComponent.java:12)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.realmSessionParamsStore(DaggerMatrixComponent.java:7)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.defaultAuthenticationService(DaggerMatrixComponent.java:13)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.injectMatrix(DaggerMatrixComponent.java:1)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.inject(DaggerMatrixComponent.java:1)
        at org.matrix.android.sdk.api.Matrix.<init>(Matrix.kt:45)
        at im.vector.app.core.di.VectorStaticModule.providesMatrix(SingletonModule.kt:13)
        at im.vector.app.core.di.VectorStaticModule_ProvidesMatrixFactory.providesMatrix(VectorStaticModule_ProvidesMatrixFactory.java:3)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerVectorApplication_HiltComponents_SingletonC.java:1426)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:14)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.authenticationService(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.injectVectorApplication2(DaggerVectorApplication_HiltComponents_SingletonC.java:1)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.injectVectorApplication(DaggerVectorApplication_HiltComponents_SingletonC.java:1)
        at im.vector.app.Hilt_VectorApplication.hiltInternalInject(Hilt_VectorApplication.java:17)
        at im.vector.app.Hilt_VectorApplication.onCreate(Hilt_VectorApplication.java:1)
        at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:1)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1198)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
        ... 8 more
Caused by: android.security.KeyStoreException: Signature/MAC verification failed

[09-18 16:54:14.689 7150:7150 E/JitsiMeetSDK]
JitsiMeetUncaughtExceptionHandler FATAL ERROR
java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: javax.crypto.AEADBadTagException
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: javax.crypto.AEADBadTagException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.decryptBytesM(SecretStoringUtils.kt:38)
        at org.matrix.android.sdk.api.securestorage.SecretStoringUtils.loadSecureSecretBytes(SecretStoringUtils.kt:25)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.extractKeyForDatabase(RealmKeysUtils.kt:34)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.getRealmEncryptionKey(RealmKeysUtils.kt:26)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.configureEncryption(RealmKeysUtils.kt:11)
        at org.matrix.android.sdk.internal.auth.AuthModule$Companion.providesRealmConfiguration(AuthModule.kt:52)
        at org.matrix.android.sdk.internal.auth.AuthModule.providesRealmConfiguration(AuthModule.kt:3)
        at org.matrix.android.sdk.internal.auth.AuthModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(AuthModule_ProvidesRealmConfigurationFactory.java:1)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.authDatabaseRealmConfiguration(DaggerMatrixComponent.java:12)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.realmSessionParamsStore(DaggerMatrixComponent.java:7)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.defaultAuthenticationService(DaggerMatrixComponent.java:13)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.injectMatrix(DaggerMatrixComponent.java:1)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent$MatrixComponentImpl.inject(DaggerMatrixComponent.java:1)
        at org.matrix.android.sdk.api.Matrix.<init>(Matrix.kt:45)
        at im.vector.app.core.di.VectorStaticModule.providesMatrix(SingletonModule.kt:13)
        at im.vector.app.core.di.VectorStaticModule_ProvidesMatrixFactory.providesMatrix(VectorStaticModule_ProvidesMatrixFactory.java:3)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerVectorApplication_HiltComponents_SingletonC.java:1426)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:14)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.authenticationService(DaggerVectorApplication_HiltComponents_SingletonC.java:3)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.injectVectorApplication2(DaggerVectorApplication_HiltComponents_SingletonC.java:1)
        at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$SingletonCImpl.injectVectorApplication(DaggerVectorApplication_HiltComponents_SingletonC.java:1)
        at im.vector.app.Hilt_VectorApplication.hiltInternalInject(Hilt_VectorApplication.java:17)
        at im.vector.app.Hilt_VectorApplication.onCreate(Hilt_VectorApplication.java:1)
        at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:1)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1198)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
        ... 8 more
Caused by: android.security.KeyStoreException: Signature/MAC verification failed

[09-18 16:54:14.689 7150:7150 E/JitsiMeetSDK]
        at im.vector.app.Hilt_VectorApplication.hiltInternalInject(Hilt_VectorApplication.java:17)
        at im.vector.app.Hilt_VectorApplication.onCreate(Hilt_VectorApplication.java:1)
        at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:1)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1198)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
        ... 8 more
Caused by: android.security.KeyStoreException: Signature/MAC verification failed
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1306)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:176)
        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        ... 35 more

[09-18 16:54:14.693 1113:6865 W/ActivityTaskManager]
  Force finishing activity im.vector.app/im.vector.application.features.Alias

[09-18 16:54:14.750 1113:2422 I/ActivityManager]
Process im.vector.app (pid 7150) has died: fg  TOP 

[09-18 16:54:15.196 1113:1275 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{61462d9 u0 im.vector.app/im.vector.application.features.Alias t-1 f}}
```

**Comment by Tynach** [comment]
This problem finally went away for me. I don't exactly know what solved it, but since I use the F-Droid version, I tried installing the 'armeabi-v7a' version, and then the 'armeabi-v8a' version, and I attempted to launch the application after each time.

Eventually one of them started working, and I switched to the other one, and it worked too. I don't know which one made it start working anymore, but I guess it might have something to do with the CPU-architecture-sensitive parts of the app.
