### ISSUE TITLE
Application crash due to missing view

### ISSUE THREAD

**Issue by akhilvarkey** [vector-im/element-android#3961]
### Steps to reproduce

1. Launch the application.
2. See application crash.

### What did you expect?

Normal application launch.

### What happened?

Application Crash due to missing view - waiting view.

CI build for this [commit](https://github.com/vector-im/element-android/commit/377c4e00a342b88a788847ae38dd99f3174aade1) .

**Stactkrace**
```
FATAL EXCEPTION: main
Process: im.vector.app.debug, PID: 30117
java.lang.RuntimeException: Unable to start activity ComponentInfo{im.vector.app.debug/im.vector.app.features.home.HomeActivity}: java.lang.NullPointerException: Missing required view with ID: im.vector.app.debug:id/waiting_view
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Missing required view with ID: im.vector.app.debug:id/waiting_view
	at im.vector.app.databinding.MergeOverlayWaitingViewBinding.bind(MergeOverlayWaitingViewBinding.java:106)
	at im.vector.app.databinding.ActivityHomeBinding.bind(ActivityHomeBinding.java:103)
	at im.vector.app.databinding.ActivityHomeBinding.inflate(ActivityHomeBinding.java:69)
	at im.vector.app.databinding.ActivityHomeBinding.inflate(ActivityHomeBinding.java:59)
	at im.vector.app.features.home.HomeActivity.getBinding(HomeActivity.kt:152)
	at im.vector.app.features.home.HomeActivity.getBinding(HomeActivity.kt:87)
	at im.vector.app.core.platform.VectorBaseActivity.onCreate(VectorBaseActivity.kt:234)
	at im.vector.app.features.home.HomeActivity.onCreate(HomeActivity.kt:171)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
```

Please take a look @bmarty.

### Application version and app store

Element (F-Droid)  debug build - https://buildkite.com/matrix-dot-org/element-android/builds/3251#e9e0255a-337b-455f-a5a1-9a172bbaac91

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Thanks for reporting, I've just seen that, I'm on it

**Comment by akhilvarkey** [comment]
Great. Sorry for the noise then.
