### ISSUE TITLE
[Crash] Leaving RoomDetails

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#4123]
### Steps to reproduce

1. Go on Room  and leave there

### What happened?

```
2021-09-30 10:43:14.651 4106-4106/chat.dns.messenger.debug E/WindowManager: android.view.WindowLeaked: Activity im.vector.app.features.roomprofile.RoomProfileActivity has leaked window DecorView@27a67bc[RoomProfileActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:733)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:717)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
        at android.app.Dialog.show(Dialog.java:340)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
        at im.vector.lib.ui.styles.dialogs.MaterialProgressDialog.show(MaterialProgressDialog.kt:35)
        at im.vector.lib.ui.styles.dialogs.MaterialProgressDialog.show$default(MaterialProgressDialog.kt:27)
        at im.vector.app.core.platform.VectorBaseFragment.showLoadingDialog(VectorBaseFragment.kt:207)
        at im.vector.app.core.platform.VectorBaseFragment.showLoading(VectorBaseFragment.kt:141)
        at im.vector.app.features.roomprofile.RoomProfileFragment$onViewCreated$1.invoke(RoomProfileFragment.kt:121)
        at im.vector.app.features.roomprofile.RoomProfileFragment$onViewCreated$1.invoke(RoomProfileFragment.kt:119)
        at im.vector.app.core.platform.VectorBaseFragment.observeViewEvents$lambda-2(VectorBaseFragment.kt:248)
        at im.vector.app.core.platform.VectorBaseFragment.$r8$lambda$OJ1ThmoY5ioABRJ_1Es4F3L8z5Y(Unknown Source:0)
        at im.vector.app.core.platform.VectorBaseFragment$$ExternalSyntheticLambda0.accept(Unknown Source:6)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Your phone model

Oneplus N10

### Operating system version

Android 11

### Application version and app store

Develop

### Homeserver

messenger.3dns.eu

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Not reproduced on Android 10.
By "leave there" you mean leave the room, right? (just to be sure). I get that from the stack trace.
Maybe something new in Android 11 or depending on your device configuration.

I guess we should hide the MaterialProgressDialog when the room is left, or probably in a more generic way when the VectorBaseFragment is destroyed (or paused?).

**Comment by DoM1niC** [comment]
is fixed now for me and close it 👍🏻
