### ISSUE TITLE
Crash when codeblocks contain emojis

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#4794]
### Steps to reproduce

1. Enable markdown
2. Open a room or send a message to a room with a code block containing :face_exhaling: 

#### What did you expect?
No crash

#### What happened instead?
We're seeing a variant of https://github.com/vector-im/element-android/issues/4691 but in codeblocks

```
Thread: main, Exception: com.airbnb.epoxy.ImmutableModelException: The model was changed during the bind call. Position: 2 Model: MessageBlockCodeItem_{message=VectorCharSequence(value=😮‍💨

Epoxy attribute fields on a model cannot be changed once the model is added to a controller. Check that these fields are not updated, or that the assigned objects are not mutated, outside of the buildModels method. The only exception is if the change is made inside an Interceptor callback. Consider using an interceptor if you need to change a model after it is added to the controller and before it is set on the adapter. If the model is already set on the adapter then you must call `requestModelBuild` instead to recreate all models.
     at com.airbnb.epoxy.EpoxyModel.validateStateHasNotChangedSinceAdded(EpoxyModel.java:466)
     at im.vector.app.features.home.room.detail.timeline.item.MessageBlockCodeItem_.handlePostBind(MessageBlockCodeItem_.java:56)
     at im.vector.app.features.home.room.detail.timeline.item.MessageBlockCodeItem_.handlePostBind(MessageBlockCodeItem_.java:26)
     at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:77)
     at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:118)
     at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:20)
```

### Operating system version

android 10 (MIUI 12.0.3.0)

### Application version and app store

1.3.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in EA 1.3.13
