### ISSUE TITLE
Crash when viewing source which contains an emoji

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#4796]
### Steps to reproduce

1. Enable the settings option - developer mode 
2. open or submit to an unencrypted room the :face_exhaling: emoji 
3. View source of the message containing the emoji   

#### What did you expect?
No crash!

#### What happened instead?
App crashes due to https://github.com/BillCarsonFr/JsonViewer/blob/master/jsonviewer/src/main/java/org/billcarsonfr/jsonviewer/ValueItem.kt#L20 needing to apply the emoji fix  https://github.com/vector-im/element-android/pull/4698

```
Thread: main, Exception: com.airbnb.epoxy.ImmutableModelException: The model was changed during the bind call. Position: 5 Model: ValueItem_{text="displayname" : "😮‍💨",...

at com.airbnb.epoxy.EpoxyModel.validateStateHasNotChangedSinceAdded(EpoxyModel.java:3)
at org.billcarsonfr.jsonviewer.ValueItem_.handlePostBind(ValueItem_.java:2)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:27)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:3)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
```

https://github.com/matrix-org/element-android-rageshakes/issues/30406
https://github.com/matrix-org/element-android-rageshakes/issues/30378

### Operating system version

android 10 (MIUI 12.0.3.0)

### Application version and app store

1.3.12

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in 1.3.15
