### ISSUE TITLE
Crash in timeline: sublist

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4959]
The crash is at line is https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt#L195, and there is another occurrence of `sublist` in this file.

Maybe some missing `synchronized` and maybe make the code more robust when using `sublist` (check the list size)

Reported by the PlayStore:

```
java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.subListRangeCheck (ArrayList.java:1016)
  at java.util.ArrayList.subList (ArrayList.java:1008)
  at im.vector.app.features.home.room.detail.timeline.TimelineEventController$listUpdateCallback$1.onChanged (TimelineEventController.kt:9)
  at androidx.recyclerview.widget.BatchingListUpdateCallback.dispatchLastEvent (BatchingListUpdateCallback.java:2)
  at androidx.recyclerview.widget.BatchingListUpdateCallback.onRemoved (BatchingListUpdateCallback.java:4)
  at androidx.recyclerview.widget.DiffUtil$DiffResult.dispatchUpdatesTo (DiffUtil.java:19)
  at im.vector.app.features.home.room.detail.timeline.TimelineEventController.submitSnapshot$lambda-1 (TimelineEventController.kt:5)
  at im.vector.app.features.home.room.detail.timeline.TimelineEventController.$r8$lambda$3TTrlC1CKqzF1pipfR2kqQsG6m8 (Unknown Source)
```

and rageshakes:
https://github.com/matrix-org/element-android-rageshakes/issues/31789

```
Thread: Timeline_Building_Thread, Exception: java.lang.IndexOutOfBoundsException: toIndex = 100
at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
at java.util.ArrayList.subList(ArrayList.java:1008)
at im.vector.app.features.home.room.detail.timeline.TimelineEventController$listUpdateCallback$1.onChanged(TimelineEventController.kt:9)
at androidx.recyclerview.widget.BatchingListUpdateCallback.dispatchLastEvent(BatchingListUpdateCallback.java:2)
at androidx.recyclerview.widget.BatchingListUpdateCallback.onRemoved(BatchingListUpdateCallback.java:4)
at androidx.recyclerview.widget.DiffUtil$DiffResult.dispatchUpdatesTo(DiffUtil.java:19)
at im.vector.app.features.home.room.detail.timeline.TimelineEventController.submitSnapshot$lambda-1(TimelineEventController.kt:5)
at im.vector.app.features.home.room.detail.timeline.TimelineEventController.$r8$lambda$3TTrlC1CKqzF1pipfR2kqQsG6m8(Unknown Source:0)
```

**Comment by bmarty** [comment]
Fixed in 1.3.15
