### ISSUE TITLE
Crash when sharing files stored on nextcloud

### ISSUE THREAD

**Issue by akallabeth** [vector-im/element-android#5236]
### Steps to reproduce

1. Where are you starting? What can you see?
Trying to share a file/image from within a room or file manager (with destination element)

#### What did you expect?
File shared

#### What happened instead?
Crash

[log.txt](https://github.com/vector-im/element-android/files/8067004/log.txt)

### Your phone model

PixelXL

### Operating system version

Android 10 (Lineageos, no Gapps)

### Application version and app store

Element 1.4.0 from F-Droid

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment]
thanks for providing the logs, this looks like a threading issue within Element, our attachment/photo processing is happening on the main thread (which android will block if it involves and networking)

```
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: android.os.NetworkOnMainThreadException
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:389)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at java.net.Socket.connect(Socket.java:621)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:185)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:205)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:111)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:169)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:187)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at com.owncloud.android.providers.DocumentsStorageProvider.openDocument(DocumentsStorageProvider.java:211)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1317)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at android.provider.DocumentsProvider.openTypedAssetFileImpl(DocumentsProvider.java:1427)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at android.provider.DocumentsProvider.openTypedAssetFile(DocumentsProvider.java:1359)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:511)
02-15 08:46:33.301 26927 32523 E DownloadFileRemoteOperation: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
```


```
02-15 08:46:33.320 26540 26540 E AndroidRuntime: FATAL EXCEPTION: main
02-15 08:46:33.320 26540 26540 E AndroidRuntime: Process: im.vector.app, PID: 26540
02-15 08:46:33.320 26540 26540 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	... 1 more
02-15 08:46:33.320 26540 26540 E AndroidRuntime: Caused by: java.io.FileNotFoundException: Error downloading file: someimagefile.jpg
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at im.vector.lib.multipicker.utils.ImageUtils.getOrientation(ImageUtils.kt:1)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at im.vector.lib.multipicker.utils.ContentResolverUtilKt.toMultiPickerImageType(ContentResolverUtil.kt:10)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at im.vector.lib.multipicker.MediaPicker.getSelectedFiles(MediaPicker.kt:8)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at im.vector.app.features.attachments.AttachmentsHelper.onMediaResult(AttachmentsHelper.kt:3)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at im.vector.app.features.home.room.detail.TimelineFragment$attachmentMediaActivityResultLauncher$1.invoke(TimelineFragment.kt:4)
02-15 08:46:33.320 26540 26540 E AndroidRuntime: 	at im.vector.app.features.home.room.detail.TimelineFragment$attachmentMediaActivityResultLauncher$1.invoke(TimelineFragment.kt:5)
```

**Comment by akallabeth** [comment]
The following patch resolves the issue for me, but not sure this is appropriate to be upstreamed:

```
diff --git a/multipicker/src/main/java/im/vector/lib/multipicker/utils/ImageUtils.kt b/multipicker/src/main/java/im/vector/lib/multipicker/utils/ImageUtils.kt
index a3d69ae8c..5dae4b5fa 100644
--- a/multipicker/src/main/java/im/vector/lib/multipicker/utils/ImageUtils.kt
+++ b/multipicker/src/main/java/im/vector/lib/multipicker/utils/ImageUtils.kt
@@ -23,35 +23,51 @@ import android.graphics.ImageDecoder
 import android.net.Uri
 import android.os.Build
 import androidx.exifinterface.media.ExifInterface
+import kotlinx.coroutines.async
+import kotlinx.coroutines.runBlocking
 import timber.log.Timber
 
 object ImageUtils {
 
     fun getBitmap(context: Context, uri: Uri): Bitmap? {
-        return try {
-            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
-                ImageDecoder.decodeBitmap(ImageDecoder.createSource(context.contentResolver, uri))
-            } else {
-                context.contentResolver.openInputStream(uri)?.use { inputStream ->
-                    BitmapFactory.decodeStream(inputStream)
+        var bitmap: Bitmap? = null
+        runBlocking {
+            val job = async {
+                try {
+                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
+                        ImageDecoder.decodeBitmap(ImageDecoder.createSource(context.contentResolver, uri))
+                    } else {
+                        context.contentResolver.openInputStream(uri)?.use { inputStream ->
+                            BitmapFactory.decodeStream(inputStream)
+                        }
+                    }
+                } catch (e: Exception) {
+                    Timber.e(e, "Cannot decode Bitmap: %s", uri.toString())
+                    null
                 }
             }
-        } catch (e: Exception) {
-            Timber.e(e, "Cannot decode Bitmap: %s", uri.toString())
-            null
+            bitmap = job.await()
         }
+
+        return bitmap
     }
 
     fun getOrientation(context: Context, uri: Uri): Int {
         var orientation = 0
-        context.contentResolver.openInputStream(uri)?.use { inputStream ->
-            try {
-                ExifInterface(inputStream).let {
-                    orientation = it.rotationDegrees
-                }
-            } catch (e: Exception) {
-                Timber.e(e, "Cannot read orientation: %s", uri.toString())
+        runBlocking {
+            val job = async {
+                context.contentResolver.openInputStream(uri)?.use {
+                    inputStream ->
+                        try {
+                            ExifInterface(inputStream).let {
+                                orientation = it.rotationDegrees
+                            }
+                        } catch (e: Exception) {
+                            Timber.e(e, "Cannot read orientation: %s", uri.toString())
+                        }
+                    }
             }
+            job.await()
         }
         return orientation
     }
```

**Comment by akallabeth** [comment]
FYI: I´ve pushed a fix to https://github.com/nextcloud/android/pull/9921 as the `DocumentProvider` should prevent running network related stuff on main thread anyway, but moving this to background tasks would still be a good idea for element (you never know which other providers expose such behavior)

**Comment by ouchadam** [comment]
I had a quick go at fixing this with https://github.com/vector-im/element-android/pull/5427 however we'll need to update all of the `ContentResolver` usages within the `muiltipicker` module or force all the entry points to be off the main thread in the `AttachmentsHelper`
