### ISSUE TITLE
[Nightly build] Crash on startup with RealmMigrationNeededException

### ISSUE THREAD

**Issue by davidmehren** [vector-im/element-android#5243]
### Steps to reproduce

1. Try to start the app
2. Observe immediate crash

#### What did you expect?
The app works normally, as it did before upgrading to the latest nightly version.

#### What happened instead?
The app crashes. Stacktrace:
```
02-16 10:08:15.706 18193 18193 D AndroidRuntime: Shutting down VM
02-16 10:08:15.707 18193 18193 E AndroidRuntime: FATAL EXCEPTION: main
02-16 10:08:15.707 18193 18193 E AndroidRuntime: Process: im.vector.app.debug, PID: 18193
02-16 10:08:15.707 18193 18193 E AndroidRuntime: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
02-16 10:08:15.707 18193 18193 E AndroidRuntime: - Property 'HomeServerCapabilitiesEntity.canChangeDisplayName' has been added.
02-16 10:08:15.707 18193 18193 E AndroidRuntime: - Property 'HomeServerCapabilitiesEntity.canChangeAvatar' has been added.
02-16 10:08:15.707 18193 18193 E AndroidRuntime: - Property 'HomeServerCapabilitiesEntity.canChange3pid' has been added.
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6730)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
02-16 10:08:15.707 18193 18193 E AndroidRuntime: - Property 'HomeServerCapabilitiesEntity.canChangeDisplayName' has been added.
02-16 10:08:15.707 18193 18193 E AndroidRuntime: - Property 'HomeServerCapabilitiesEntity.canChangeAvatar' has been added.
02-16 10:08:15.707 18193 18193 E AndroidRuntime: - Property 'HomeServerCapabilitiesEntity.canChange3pid' has been added.
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:141)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:108)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.Realm.<init>(Realm.java:159)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.Realm.createInstance(Realm.java:495)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.RealmCache.createInstance(RealmCache.java:494)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:461)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:424)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.database.SessionRealmConfigurationFactory.create(SessionRealmConfigurationFactory.kt:79)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.SessionModule$Companion.providesRealmConfiguration(SessionModule.kt:193)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.SessionModule.providesRealmConfiguration(Unknown Source:2)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(SessionModule_ProvidesRealmConfigurationFactory.java:40)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:30)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:11)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:270)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:60)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:2260)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.SessionManager.getOrCreateSession(SessionManager.kt:42)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:78)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:167)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
02-16 10:08:15.707 18193 18193 E AndroidRuntime: 	... 9 more
02-16 10:08:15.707 18193 18193 V VectorUncaughtExceptionHandler: Uncaught exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
02-16 10:08:15.707 18193 18193 V VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChangeDisplayName' has been added.
02-16 10:08:15.707 18193 18193 V VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChangeAvatar' has been added.
02-16 10:08:15.707 18193 18193 V VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChange3pid' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 210634000
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: Element Version : 1.4.2-dev [210634000] (G-b6131)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: SDK Version : 1.4.2 (6c4f3893)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: Phone : Pixel 6 Pro (8069835 12 REL)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: Memory statuses 
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: usedSize   8 MB
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: freeSize   247 MB
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: totalSize   256 MB
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: Thread: main, Exception: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChangeDisplayName' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChangeAvatar' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChange3pid' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6730)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.os.Looper.loopOnce(Looper.java:201)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:288)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChangeDisplayName' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChangeAvatar' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: - Property 'HomeServerCapabilitiesEntity.canChange3pid' has been added.
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.BaseRealm.<init>(BaseRealm.java:141)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.BaseRealm.<init>(BaseRealm.java:108)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.Realm.<init>(Realm.java:159)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.Realm.createInstance(Realm.java:495)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.RealmCache.createInstance(RealmCache.java:494)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:461)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at io.realm.Realm.getInstance(Realm.java:424)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.database.SessionRealmConfigurationFactory.create(SessionRealmConfigurationFactory.kt:79)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.SessionModule$Companion.providesRealmConfiguration(SessionModule.kt:193)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.SessionModule.providesRealmConfiguration(Unknown Source:2)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(SessionModule_ProvidesRealmConfigurationFactory.java:40)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:30)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.SessionModule_ProvidesRealmConfigurationFactory.get(SessionModule_ProvidesRealmConfigurationFactory.java:11)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:270)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:60)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:36)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.session.DaggerSessionComponent.session(DaggerSessionComponent.java:2260)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.SessionManager.getOrCreateSession(SessionManager.kt:42)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:78)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:167)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
02-16 10:08:15.708 18193 18193 E VectorUncaughtExceptionHandler: 	... 9 more
```

### Your phone model

Pixel 6 Pro

### Operating system version

Android 12

### Application version and app store

1.4.2-dev [210634000] (G-b6131) from fdroid.krombel.de

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by ouchadam** [comment]
fixed by https://github.com/vector-im/element-android/pull/5245
