### ISSUE TITLE
SpaceMenuRobot unable to find view when leaving space during CI sanity test

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-android#5269]
This is failing in nightly CI at the moment.

![en-allScreensTest-Fri-February-18-164828](https://user-images.githubusercontent.com/1917473/154944761-2785c3d5-a37f-452a-ae22-378744cb8cac.jpeg)

```
02-18 16:48:33.295  3259  3283 E TestRunner: failed: allScreensTest(im.vector.app.ui.UiAllScreensSanityTest)
02-18 16:48:33.295  3259  3283 E TestRunner: ----- begin exception -----
02-18 16:48:33.302  3259  3275 I ector.app.debu: Waiting for a blocking GC ProfileSaver
02-18 16:48:33.302  3259  3283 E TestRunner: androidx.test.espresso.PerformException: Error performing 'wait for a specific view <view.getId() is <2131296980/im.vector.app.debug:id/groupListView>> to be displayed' on view 'view.getRootView() to equal view'.
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:9)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.espresso.tools.WaitActivityKt.waitUntilViewVisible(WaitActivity.kt:35)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.robot.space.SpaceMenuRobot.leaveSpace(SpaceMenuRobot.kt:112)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.UiAllScreensSanityTest$allScreensTest$5$3.invoke(UiAllScreensSanityTest.kt:120)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.UiAllScreensSanityTest$allScreensTest$5$3.invoke(UiAllScreensSanityTest.kt:109)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.robot.space.SpaceRobot.spaceMenu(SpaceRobot.kt:35)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.UiAllScreensSanityTest$allScreensTest$5.invoke(UiAllScreensSanityTest.kt:109)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.UiAllScreensSanityTest$allScreensTest$5.invoke(UiAllScreensSanityTest.kt:100)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.robot.ElementRobot.space(ElementRobot.kt:153)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.ui.UiAllScreensSanityTest.allScreensTest(UiAllScreensSanityTest.kt:100)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
02-18 16:48:33.302  3259  3283 E TestRunner: Caused by: java.util.concurrent.TimeoutException
02-18 16:48:33.302  3259  3283 E TestRunner: 	at im.vector.app.EspressoExtKt$waitForView$1.perform(EspressoExt.kt:125)
02-18 16:48:33.302  3259  3283 E TestRunner: 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:
02-18 16:48:33.303  3259  3283 E TestRunner: ----- end exception -----
```

**Comment by michaelkaye** [comment]
This is still occuring - the issue is that it finishes deleting a space and attempts to get back to the above screenshot, which is showing the groupListView, but Espresso is not detecting it correctly.

**Comment by michaelkaye** [comment]
The code in question is the last line in leaveSpace() in SpaceMenuRobot.kt
