### ISSUE TITLE
CI Failure: io.realm.exceptions.RealmFileException because path does not exist

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-android#5385]
```
02-28 17:57:16.515  2865  2897 E AndroidRuntime: FATAL EXCEPTION: Crypto_Thread
02-28 17:57:16.515  2865  2897 E AndroidRuntime: Process: org.matrix.android.sdk.test, PID: 2865
02-28 17:57:16.515  2865  2897 E AndroidRuntime: io.realm.exceptions.RealmFileException: Directory at path '/data/user/0/org.matrix.android.sdk.test/files/61c4ee988f90372e8fb60133ecbb4001/crypto_store.realm.lock' does not exist. (open("/data/user/0/org.matrix.android.sdk.test/files/61c4ee988f90372e8fb60133ecbb4001/crypto_store.realm.lock") failed: No such file or directory Path: /data/user/0/org.matrix.android.sdk.test/files/61c4ee988f90372e8fb60133ecbb4001/crypto_store.realm.lock
02-28 17:57:16.515  2865  2897 E AndroidRuntime: Exception backtrace:
02-28 17:57:16.515  2865  2897 E AndroidRuntime: <backtrace not supported on this platform>) (/data/user/0/org.matrix.android.sdk.test/files/61c4ee988f90372e8fb60133ecbb4001/crypto_store.realm.lock) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: NOT_FOUND.
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:141)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:108)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.Realm.<init>(Realm.java:159)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.Realm.createInstance(Realm.java:495)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.RealmCache.createInstance(RealmCache.java:494)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:461)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:424)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.store.db.HelperKt.doWithRealm(Helper.kt:32)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore.getDeviceTrackingStatuses(RealmCryptoStore.kt:1017)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.DeviceListManager$1.invokeSuspend(DeviceListManager.kt:86)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-28 17:57:16.515  2865  2897 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
02-28 17:57:16.521  2865  2897 I Process : Sending signal. PID: 2865 SIG: 9
02-28 17:57:16.565  1666  1666 I Zygote  : Process 2865 exited due to signal (9)
```

**Comment by michaelkaye** [comment]
https://github.com/vector-im/element-android/runs/5363222723?check_suite_focus=true#step:14:289 for the test suite fail

https://github.com/vector-im/element-android/suites/5477507576/artifacts/174706603 for the log files
