### ISSUE TITLE
[Create room] Picture doesn't not displayed

### ISSUE THREAD

**Issue by Claire1817** [vector-im/element-android#5402]
### Steps to reproduce

Create a room and set a picture
Logs:
```
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder: android.os.NetworkOnMainThreadException
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork([StrictMode.java:1605](http://strictmode.java:1605/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.Platform.blockGuardOnNetwork([Platform.java:426](http://platform.java:426/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket([ConscryptEngineSocket.java:827](http://conscryptenginesocket.java:827/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable([ConscryptEngineSocket.java:815](http://conscryptenginesocket.java:815/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$[SSLInputStream.read](http://sslinputstream.read/)([ConscryptEngineSocket.java:788](http://conscryptenginesocket.java:788/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [okio.InputStreamSource.read](http://okio.inputstreamsource.read/)(JvmOkio.kt:93)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.AsyncTimeout$source$[1.read](http://1.read/)(AsyncTimeout.kt:125)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.http1.Http1ExchangeCodec$[ChunkedSource.read](http://chunkedsource.read/)(Http1ExchangeCodec.kt:408)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [okhttp3.internal.connection.Exchange](http://okhttp3.internal.connection.exchange/)$[ResponseBodySource.read](http://responsebodysource.read/)(Exchange.kt:276)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [okio.RealBufferedSource.read](http://okio.realbufferedsource.read/)(RealBufferedSource.kt:189)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.GzipSource.consumeHeader(GzipSource.kt:104)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [okio.GzipSource.read](http://okio.gzipsource.read/)(GzipSource.kt:62)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at com.squareup.moshi.JsonUtf8Reader.nextNonWhitespace([JsonUtf8Reader.java:1097](http://jsonutf8reader.java:1097/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at com.squareup.moshi.JsonUtf8Reader.doPeek([JsonUtf8Reader.java:337](http://jsonutf8reader.java:337/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at com.squareup.moshi.JsonUtf8Reader.peek([JsonUtf8Reader.java:206](http://jsonutf8reader.java:206/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson([NullSafeJsonAdapter.java:38](http://nullsafejsonadapter.java:38/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at com.squareup.moshi.JsonAdapter.fromJson([JsonAdapter.java:58](http://jsonadapter.java:58/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [org.matrix.android](http://org.matrix.android/).sdk.internal.session.content.FileUploader.upload(FileUploader.kt:154)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [org.matrix.android](http://org.matrix.android/).sdk.internal.session.content.FileUploader.access$upload(FileUploader.kt:50)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [org.matrix.android](http://org.matrix.android/).sdk.internal.session.content.FileUploader$upload$1.invokeSuspend(Unknown Source:15)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:106)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at android.os.Looper.loop([Looper.java:223](http://looper.java:223/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7656](http://activitythread.java:7656/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at java.lang.reflect.Method.invoke(Native Method)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:592](http://runtimeinit.java:592/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:947](http://zygoteinit.java:947/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder: 	Suppressed: android.os.NetworkOnMainThreadException
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork([StrictMode.java:1605](http://strictmode.java:1605/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.Platform.blockGuardOnNetwork([Platform.java:426](http://platform.java:426/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket([ConscryptEngineSocket.java:827](http://conscryptenginesocket.java:827/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable([ConscryptEngineSocket.java:815](http://conscryptenginesocket.java:815/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [com.android.org](http://com.android.org/).conscrypt.ConscryptEngineSocket$[SSLInputStream.read](http://sslinputstream.read/)([ConscryptEngineSocket.java:788](http://conscryptenginesocket.java:788/))
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [okio.InputStreamSource.read](http://okio.inputstreamsource.read/)(JvmOkio.kt:93)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.AsyncTimeout$source$[1.read](http://1.read/)(AsyncTimeout.kt:125)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.http1.Http1ExchangeCodec$[ChunkedSource.read](http://chunkedsource.read/)(Http1ExchangeCodec.kt:408)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.Util.skipAll(Util.kt:344)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.Util.discard(Util.kt:365)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.kt:450)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.ForwardingSource.close(ForwardingSource.kt:34)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [okhttp3.internal.connection.Exchange](http://okhttp3.internal.connection.exchange/)$ResponseBodySource.close(Exchange.kt:309)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.InflaterSource.close(InflaterSource.kt:136)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.GzipSource.close(GzipSource.kt:171)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.internal.Util.closeQuietly(Util.kt:495)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.ResponseBody.close(ResponseBody.kt:192)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at okhttp3.Response.close(Response.kt:302)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [kotlin.io](http://kotlin.io/).CloseableKt.closeFinally(Closeable.kt:60)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder:     at [org.matrix.android](http://org.matrix.android/).sdk.internal.session.content.FileUploader.upload(FileUploader.kt:149)
2022-03-02 15:11:19.569 31314-31314/[im.vector.app](http://im.vector.app/).debug E/CreateRoomBodyBuilder: 		... 11 more
```

### Outcome

The pictures set during the room creation is not displayed when the room has been created.

### Your phone model

Pixel 4

### Operating system version

API 30

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in 1.4.4
