### ISSUE TITLE
[SDK] 

### ISSUE THREAD

**Issue by Simon416** [vector-im/element-android#5428]
### Description

Hi, When I start the application  i get such a crash after call 
Matrix.initialize(
            context = this,
            matrixConfiguration = MatrixConfiguration(
                roomDisplayNameFallbackProvider = RoomDisplayNameFallbackProviderImpl()
            )
        )
How can i fix it ?
I will be glad to your answer, thanks)

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to create application ru.testProject.App: javax.crypto.AEADBadTagException
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7142)
        at android.app.ActivityThread.access$1600(ActivityThread.java:262)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2160)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8128)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
     Caused by: javax.crypto.AEADBadTagException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at org.matrix.android.sdk.internal.session.securestorage.SecretStoringUtils.decryptStringM(SourceFile:11)
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.configureEncryption(SourceFile:10)
        at org.matrix.android.sdk.internal.auth.AuthModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(SourceFile:7)
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent.realmSessionParamsStore(SourceFile:7)
        at org.matrix.android.sdk.api.Matrix.<init>(SourceFile:10)
        at supportchat.ChatProvider.<init>(SourceFile:11)
        at  ru.testProject.App.onCreate(SourceFile:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7132)
        at android.app.ActivityThread.access$1600(ActivityThread.java:262) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2160) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.app.ActivityThread.main(ActivityThread.java:8128) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015) 
     Caused by: android.security.KeyStoreException: Signature/MAC verification failed
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:
        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055) 
        at org.matrix.android.sdk.internal.session.securestorage.SecretStoringUtils.decryptStringM(SourceFile:11) 
        at org.matrix.android.sdk.internal.database.RealmKeysUtils.configureEncryption(SourceFile:10) 
        at org.matrix.android.sdk.internal.auth.AuthModule_ProvidesRealmConfigurationFactory.providesRealmConfiguration(SourceFile:7) 
        at org.matrix.android.sdk.internal.di.DaggerMatrixComponent.realmSessionParamsStore(SourceFile:7) 
        at org.matrix.android.sdk.api.Matrix.<init>(SourceFile:10) 
        at supportchat.ChatProvider.<init>(SourceFile:11) 
        at ru.testProject.App.onCreate(SourceFile:18) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7132) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:262) 
        at android.app.ActivityThrea

d$H.handleMessage(ActivityThread.java:2160) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.app.ActivityThread.main(ActivityThread.java:8128) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by ouchadam** [comment]
thanks for raising! do you have an example project which can reproduce the issue?

**Comment by Samiul-Hossain** [comment]
Hi! I faced the same issue in the test device (Samsung A71) I was using for development. I was able to fix it by navigating to Settings > Security and privacy > Other security settings > Clear credentials. I guess this completely removes the corrupted keystore from the device.
