### ISSUE TITLE
Investigate CI failure: in crypto VerificationTest - Configurations cannot be different if used to open the same file

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-android#5449]
```
SEVERE: Execute org.matrix.android.sdk.internal.crypto.verification.qrcode.VerificationTest.test_aliceAndBob_scan_show: FAILED
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file.
Cached configuration:
realmDirectory: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659
realmFileName : disk_store.realm
canonicalPath: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659/disk_store.realm
key: [length: 64]
schemaVersion: 25
migration: org.matrix.android.sdk.internal.database.RealmSessionStoreMigration@3e8
deleteRealmIfMigrationNeeded: false
durability: FULL
schemaMediator: io.realm.SessionRealmModuleMediator@34525777
readOnly: false
compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@7ff7003
maxNumberOfActiveVersions: 9223372036854775807

New configuration:
realmDirectory: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659
realmFileName : disk_store.realm
canonicalPath: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659/disk_store.realm
key: [length: 64]
schemaVersion: 25
migration: org.matrix.android.sdk.internal.database.RealmSessionStoreMigration@3e8
deleteRealmIfMigrationNeeded: false
durability: FULL
schemaMediator: io.realm.SessionRealmModuleMediator@34525777
readOnly: false
compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@135cb80
maxNumberOfActiveVersions: 9223372036854775807
at io.realm.RealmCache.validateConfiguration(RealmCache.java:592)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:457)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
at io.realm.Realm.getInstance(Realm.java:424)
at org.matrix.android.sdk.internal.database.AsyncTransactionKt$awaitTransaction$2.invokeSuspend(AsyncTransaction.kt:40)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file.
Cached configuration:
realmDirectory: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659
realmFileName : disk_store.realm
canonicalPath: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659/disk_store.realm
key: [length: 64]
schemaVersion: 25
migration: org.matrix.android.sdk.internal.database.RealmSessionStoreMigration@3e8
deleteRealmIfMigrationNeeded: false
durability: FULL
schemaMediator: io.realm.SessionRealmModuleMediator@34525777
readOnly: false
compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@7ff7003
maxNumberOfActiveVersions: 9223372036854775807

New configuration:
realmDirectory: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659
realmFileName : disk_store.realm
canonicalPath: /data/user/0/org.matrix.android.sdk.test/files/dc444317237ac364b9ba990a5fba9659/disk_store.realm
key: [length: 64]
schemaVersion: 25
migration: org.matrix.android.sdk.internal.database.RealmSessionStoreMigration@3e8
deleteRealmIfMigrationNeeded: false
durability: FULL
schemaMediator: io.realm.SessionRealmModuleMediator@34525777
readOnly: false
compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@135cb80
maxNumberOfActiveVersions: 9223372036854775807
at io.realm.RealmCache.validateConfiguration(RealmCache.java:592)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:457)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
at io.realm.Realm.getInstance(Realm.java:424)
at org.matrix.android.sdk.internal.database.AsyncTransactionKt$awaitTransaction$2.invokeSuspend(AsyncTransaction.kt:40)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by michaelkaye** [comment]
Difference between the above configurations is either:
 - compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@7ff7003 (different callbacks, possibly different results?)
 - key: [length: 64] (we don't know data yet)

**Comment by michaelkaye** [comment]
This has failed on a local android studio test run of just this class, so it's reproducible outside of CI.

**Comment by michaelkaye** [comment]
> This has failed on a local android studio test run of just this class, so it's reproducible outside of CI.

Ah, but it can fail on different parts of the test each time - i've had it fail on scan_show and on sas_scan so far.

**Comment by michaelkaye** [comment]
In summary,  about 50% of the time one of the ten tests in this file fail with the above exception, in CI and on a local android-studio build. It is not the same function each time. We've ignored the tests but this issue is for us to fix and re-enable them.
