### ISSUE TITLE
Element crashes with Microsoft Swiftkey

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-android#5597]
### Steps to reproduce

Unfortunately didn't occour on every device

1. Klick on the speech to text function of Microsoft Switkey
2. Speak to your device
3. click on finished
https://youtu.be/-SLingtTR_c

#### What did you expect?
keyboard closed and i can send the message
#### What happened instead?
Element crashed

### Your phone model

later

### Operating system version

later

### Application version and app store

later

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
thanks for submitting the logs! looks like we've got some wrong threading going on

```
Thread: pool-22-thread-2, Exception: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6930)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:990)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:5099)
at android.view.View.invalidateInternal(View.java:12758)
at android.view.View.invalidate(View.java:12694)
at android.widget.TextView.invalidateRegion(TextView.java:5188)
at android.widget.TextView.invalidateCursor(TextView.java:5131)
at android.widget.TextView.spanChange(TextView.java:8090)
at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:10186)
at android.text.SpannableStringInternal.sendSpanAdded(SpannableStringInternal.java:315)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:138)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at android.text.SpannableStringInternal.(SpannableStringInternal.java:52)
at android.text.SpannableString.(SpannableString.java:30)
at android.text.SpannableString.valueOf(SpannableString.java:41)
at org.matrix.android.sdk.internal.session.room.send.pills.TextPillsUtils.transformPills(TextPillsUtils.kt:1)
at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory.createTextContent(LocalEchoEventFactory.kt:4)
at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory.createTextEvent(LocalEchoEventFactory.kt:4)
at org.matrix.android.sdk.internal.session.room.send.DefaultSendService.sendTextMessage(DefaultSendService.kt:1)
at org.matrix.android.sdk.internal.session.room.DefaultRoom.sendTextMessage(DefaultRoom.kt)
at org.matrix.android.sdk.api.session.room.send.SendService$DefaultImpls.sendTextMessage$default(SendService.kt:1)
at im.vector.app.features.home.room.detail.composer.MessageComposerViewModel$handleSendMessage$1.invoke(MessageComposerViewModel.kt:15)
at im.vector.app.features.home.room.detail.composer.MessageComposerViewModel$handleSendMessage$1.invoke(MessageComposerViewModel.kt:1)
```
