### ISSUE TITLE
Crash with Realm: Incompatible lock file

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#565]
Reported by Rageshake: https://github.com/matrix-org/riot-android-rageshakes/issues/7097

Trace:
```
Thread: NotificationDrawerManager, Exception: io.realm.exceptions.RealmFileException: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. (Incompatible lock file. Shared info version doesn't match, 771 10.) (/data/data/im.vector.riotx.debug/files/USER_ID_HASH_REDACTED_MANUALLY/disk_store.realm) in /Users/Nabil/Dev/realm/master2/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: INCOMPATIBLE_LOCK_FILE.
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.(OsSharedRealm.java:171)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
at io.realm.BaseRealm.(BaseRealm.java:136)
at io.realm.BaseRealm.(BaseRealm.java:103)
at io.realm.Realm.(Realm.java:163)
at io.realm.Realm.createInstance(Realm.java:499)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
at io.realm.Realm.getInstance(Realm.java:428)
at com.zhuinden.monarchy.Monarchy.doWithRealm(Monarchy.java:315)
at im.vector.matrix.android.internal.session.room.read.DefaultReadService.isEventRead(DefaultReadService.kt:82)
at im.vector.matrix.android.internal.session.room.DefaultRoom.isEventRead(Unknown Source:7)
at im.vector.riotx.features.notifications.OutdatedEventDetector.isMessageOutdated(OutdatedEventDetector.kt:33)
at im.vector.riotx.features.notifications.NotificationDrawerManager.refreshNotificationDrawerBg(NotificationDrawerManager.kt:213)
at im.vector.riotx.features.notifications.NotificationDrawerManager.access$refreshNotificationDrawerBg(NotificationDrawerManager.kt:46)
at im.vector.riotx.features.notifications.NotificationDrawerManager$refreshNotificationDrawer$1.run(NotificationDrawerManager.kt:174)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by bmarty** [comment]
does not seem to happen anymore (after update of Realm?)
