### ISSUE TITLE
Element crashes on startup

### ISSUE THREAD

**Issue by wjt** [vector-im/element-android#6412]
### Steps to reproduce

1. Launch the app

#### What did you expect?

The app to launch.

#### What happened instead?

An Android dialog: "Element keeps stopping".

I see the following backtrace in `adb logcat`:

```
06-29 11:07:55.475  9441  9441 E AndroidRuntime: FATAL EXCEPTION: main
06-29 11:07:55.475  9441  9441 E AndroidRuntime: Process: im.vector.app, PID: 9441
06-29 11:07:55.475  9441  9441 E AndroidRuntime: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Invalid top array size (ref: 534152, size: 0) Path:Exception backtrace:
06-29 11:07:55.475  9441  9441 E AndroidRuntime: <backtrace not supported on this platform>. (Invalid top array size (ref: 534152, size: 0) Path: /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm
06-29 11:07:55.475  9441  9441 E AndroidRuntime: Exception backtrace:
06-29 11:07:55.475  9441  9441 E AndroidRuntime: <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6733)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Invalid top array size (ref: 534152, size: 0) Path:Exception backtrace:
06-29 11:07:55.475  9441  9441 E AndroidRuntime: <backtrace not supported on this platform>. (Invalid top array size (ref: 534152, size: 0) Path: /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm
06-29 11:07:55.475  9441  9441 E AndroidRuntime: Exception backtrace:
06-29 11:07:55.475  9441  9441 E AndroidRuntime: <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:26)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.Realm.<init>(Realm.java:8)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.RealmCache.createInstance(RealmCache.java:2)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:16)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:4)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:13)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:2)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.algorithms.olm.MXOlmDecryptionFactory_Factory.get(MXOlmDecryptionFactory_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.RoomDecryptorProvider_Factory.get(RoomDecryptorProvider_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.crypto.EventDecryptor_Factory.get(EventDecryptor_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.room.summary.RoomSummaryUpdater_Factory.get(RoomSummaryUpdater_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.room.send.LocalEchoRepository_Factory.get(LocalEchoRepository_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory_Factory.get(LocalEchoEventFactory_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.call.MxCallFactory_Factory.get(MxCallFactory_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.call.CallSignalingHandler_Factory.get(CallSignalingHandler_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.call.CallEventProcessor_Factory.get(CallEventProcessor_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.SetFactory.get(SetFactory.java:10)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.database.EventInsertLiveObserver_Factory.get(EventInsertLiveObserver_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.SetFactory.get(SetFactory.java:10)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.session.DaggerSessionComponent$SessionComponentImpl.session(DaggerSessionComponent.java:1)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:3)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:84)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
06-29 11:07:55.475  9441  9441 E AndroidRuntime: 	... 9 more
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Invalid top array size (ref: 534152, size: 0) Path:Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>. (Invalid top array size (ref: 534152, size: 0) Path: /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6733)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.os.Looper.loopOnce(Looper.java:201)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.os.Looper.loop(Looper.java:288)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Invalid top array size (ref: 534152, size: 0) Path:Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>. (Invalid top array size (ref: 534152, size: 0) Path: /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.BaseRealm.<init>(BaseRealm.java:26)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.Realm.<init>(Realm.java:8)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.RealmCache.createInstance(RealmCache.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:16)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.Realm.getInstance(Realm.java:4)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:13)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.algorithms.olm.MXOlmDecryptionFactory_Factory.get(MXOlmDecryptionFactory_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.RoomDecryptorProvider_Factory.get(RoomDecryptorProvider_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.EventDecryptor_Factory.get(EventDecryptor_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.room.summary.RoomSummaryUpdater_Factory.get(RoomSummaryUpdater_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.room.send.LocalEchoRepository_Factory.get(LocalEchoRepository_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory_Factory.get(LocalEchoEventFactory_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.call.MxCallFactory_Factory.get(MxCallFactory_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.call.CallSignalingHandler_Factory.get(CallSignalingHandler_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.call.CallEventProcessor_Factory.get(CallEventProcessor_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.SetFactory.get(SetFactory.java:10)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.database.EventInsertLiveObserver_Factory.get(EventInsertLiveObserver_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.SetFactory.get(SetFactory.java:10)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.DaggerSessionComponent$SessionComponentImpl.session(DaggerSessionComponent.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:3)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:84)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	... 9 more
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Invalid top array size (ref: 534152, size: 0) Path:Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>. (Invalid top array size (ref: 534152, size: 0) Path: /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6733)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.os.Looper.loopOnce(Looper.java:201)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.os.Looper.loop(Looper.java:288)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Invalid top array size (ref: 534152, size: 0) Path:Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>. (Invalid top array size (ref: 534152, size: 0) Path: /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: Exception backtrace:
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: <backtrace not supported on this platform>) (/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106 Kind: ACCESS_ERROR.
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:11)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.BaseRealm.<init>(BaseRealm.java:26)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.Realm.<init>(Realm.java:8)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.RealmCache.createInstance(RealmCache.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:16)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at io.realm.Realm.getInstance(Realm.java:4)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore.<init>(RealmCryptoStore.kt:13)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.store.db.RealmCryptoStore_Factory.get(RealmCryptoStore_Factory.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.algorithms.olm.MXOlmDecryptionFactory_Factory.get(MXOlmDecryptionFactory_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.RoomDecryptorProvider_Factory.get(RoomDecryptorProvider_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.crypto.EventDecryptor_Factory.get(EventDecryptor_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.room.summary.RoomSummaryUpdater_Factory.get(RoomSummaryUpdater_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.room.send.LocalEchoRepository_Factory.get(LocalEchoRepository_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory_Factory.get(LocalEchoEventFactory_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.call.MxCallFactory_Factory.get(MxCallFactory_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.call.CallSignalingHandler_Factory.get(CallSignalingHandler_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.call.CallEventProcessor_Factory.get(CallEventProcessor_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.SetFactory.get(SetFactory.java:10)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.database.EventInsertLiveObserver_Factory.get(EventInsertLiveObserver_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.SetFactory.get(SetFactory.java:10)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.DefaultSession_Factory.get(DefaultSession_Factory.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:5)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at dagger.internal.DelegateFactory.get(DelegateFactory.java:2)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.session.DaggerSessionComponent$SessionComponentImpl.session(DaggerSessionComponent.java:1)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at org.matrix.android.sdk.internal.auth.DefaultAuthenticationService.getLastAuthenticatedSession(DefaultAuthenticationService.kt:3)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at im.vector.app.VectorApplication.onCreate(VectorApplication.kt:84)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
06-29 11:07:55.482  9441  9441 E JitsiMeetSDK: 	... 9 more
```

### Your phone model

Google Pixel 3

### Operating system version

Android 12

### Application version and app store

Element 1.4.20 from Google Play Store

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by wjt** [comment]
I tried and failed to extract /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm using `adb`:

```
$ adb pull /data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm .
adb: error: failed to stat remote object '/data/user/0/im.vector.app/files/6c499f4a3ba5ba2fda4dcfd928fc52f2/crypto_store.realm': Permission denied
```

I'm happy to provide more info with a bit of hand-holding, though I haven't done Android development in close to a decade and my device isn't rooted.

**Comment by aakropotkin** [comment]
I've got the same issue. Pixel 4, only notable things that may differ from a basic test suite are that I have been unable to get the "confirm your login from desktop" message to go away for several weeks. Today was the first time that someone had sent me a direct message so you might look into an edge case where a user has messages in their inbox, but hasn't confirmed their identity from another device.

A related issue being : there's something wrong with the "confirm for desktop" user flow because I made a new account from mobile and have never used it on any other device - so it should not be asking this at all.

**Comment by wjt** [comment]
OK, I reinstalled the app and I'm up and away again. I did not have any outstanding "confirm your login" requests before I did so.
