### ISSUE TITLE
Crash while cross-signing with my other Element Web device

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-android#6495]
### Steps to reproduce

1. Initiate a verification request from Element Web on my computer to Element Android on my phone
2. Use the QR Code scanning method to verify the device
3. After scanning the QR code, a spinning process indicator is shown on the phone
4. The app crashes
5. Element Web shows the green checkmark shield

#### What did you expect?

Element Android to not crash, and for verification to succeed.

#### What happened instead?

The app crashed. After reopening Element Android, in Security & Privacy it says:

	  Cross-Signing is enabled
	  Keys are trusted.
	  Private keys are not known

I'm not sure whether the last line is a cause for concern.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 12

### Application version and app store

Element version 1.4.25 [40104252] (G-b9267), Matrix SDK Version 1.4.25 (1f34d368), olm version 3.2.12

### Homeserver

amorgan.xyz

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
thanks for linking the rageshake! 

To save a click...

```
Thread: Crypto_Thread, Exception: org.matrix.olm.OlmException: invalid session ptr
at org.matrix.olm.CommonSerializeUtils.serialize(CommonSerializeUtils.java:7)
at org.matrix.olm.OlmInboundGroupSession.writeObject(OlmInboundGroupSession.java:1)
at java.lang.reflect.Method.invoke(Native Method)
```
