### ISSUE TITLE
Crash on opening any room/dialog on Nexus 10

### ISSUE THREAD

**Issue by rkfg** [vector-im/element-android#6631]
### Steps to reproduce

I know it's an ancient tablet but Element worked on it before. Opening any dialog causes the app to crash. Logcat shows this:
```
W/linker  ( 9054): libopuscodec.so: unused DT entry: type 0x6ffffef5 arg 0x30b8
W/linker  ( 9054): libopuscodec.so: unused DT entry: type 0x6ffffffe arg 0x477c
W/linker  ( 9054): libopuscodec.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker  ( 9054): libopusenc.so: unused DT entry: type 0x6ffffef5 arg 0x994
W/linker  ( 9054): libopusenc.so: unused DT entry: type 0x6ffffffe arg 0x954
W/linker  ( 9054): libopusenc.so: unused DT entry: type 0x6fffffff arg 0x2
E/art     ( 9054): dlopen("/data/app/im.vector.app-1/lib/arm/libopuscodec.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "opus_projection_encoder_ctl" referenced by "libopusenc.so"...
D/AndroidRuntime( 9054): Shutting down VM
V/JitsiMeetSDK( 9054): Execute transaction in 29 millis
V/JitsiMeetSDK( 9054): [Timeline] Has loaded 10 items from storage in BACKWARDS 
E/JitsiMeetSDK( 9054): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 9054): java.lang.RuntimeException: Unable to start activity ComponentInfo{im.vector.app/im.vector.app.features.home.room.detail.RoomDetailActivity}: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK( 9054): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/JitsiMeetSDK( 9054): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/JitsiMeetSDK( 9054): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/JitsiMeetSDK( 9054): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/JitsiMeetSDK( 9054): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/JitsiMeetSDK( 9054): 	at android.os.Looper.loop(Looper.java:135)
E/JitsiMeetSDK( 9054): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/JitsiMeetSDK( 9054): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 9054): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/JitsiMeetSDK( 9054): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/JitsiMeetSDK( 9054): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/JitsiMeetSDK( 9054): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK( 9054): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 9054): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/JitsiMeetSDK( 9054): 	at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:12)
E/JitsiMeetSDK( 9054): 	at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:34)
E/JitsiMeetSDK( 9054): 	at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$3.invoke(MavericksExtensions.kt:10)
E/JitsiMeetSDK( 9054): 	at im.vector.app.features.home.room.detail.TimelineFragment$special$$inlined$fragmentViewModel$default$3.invoke(MavericksExtensions.kt:1)
E/JitsiMeetSDK( 9054): 	at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:2)
E/JitsiMeetSDK( 9054): 	at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:1)
E/JitsiMeetSDK( 9054): 	at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:5)
E/JitsiMeetSDK( 9054): 	at com.airbnb.mvrx.lifecycleAwareLazy$initializeWhenCreated$1.onCreate(lifecycleAwareLazy.kt:1)
E/JitsiMeetSDK( 9054): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:8)
E/JitsiMeetSDK( 9054): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
E/JitsiMeetSDK( 9054): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:45)
E/JitsiMeetSDK( 9054): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
E/JitsiMeetSDK( 9054): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:9)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:122)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:9)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
E/JitsiMeetSDK( 9054): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:12)
E/JitsiMeetSDK( 9054): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
E/JitsiMeetSDK( 9054): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
E/JitsiMeetSDK( 9054): 	at android.app.Activity.performStart(Activity.java:6006)
E/JitsiMeetSDK( 9054): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
E/JitsiMeetSDK( 9054): 	... 10 more
E/JitsiMeetSDK( 9054): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "opus_projection_encoder_ctl" referenced by "libopusenc.so"...
E/JitsiMeetSDK( 9054): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/JitsiMeetSDK( 9054): 	at java.lang.System.loadLibrary(System.java:988)
E/JitsiMeetSDK( 9054): 	at im.vector.opusencoder.OggOpusEncoder.<clinit>(OggOpusEncoder.kt:1)
E/JitsiMeetSDK( 9054): 	at im.vector.app.features.voice.VoiceRecorderL.<init>(VoiceRecorderL.kt:4)
E/JitsiMeetSDK( 9054): 	at im.vector.app.features.voice.VoiceRecorderProvider.provideVoiceRecorder(VoiceRecorderProvider.kt:5)
E/JitsiMeetSDK( 9054): 	at im.vector.app.features.home.room.detail.composer.AudioMessageHelper.<init>(AudioMessageHelper.kt:4)
E/JitsiMeetSDK( 9054): 	at im.vector.app.DaggerVectorApplication_HiltComponents_SingletonC$MavericksViewModel
```
Looks like a Jitsi issue, I wish it was possible to disable it. The rest of the app (settings and room list) works fine and the tablet user doesn't need conferences. Logs sent.

#### What did you expect?
It should work

#### What happened instead?
It crashes

### Your phone model

Nexus 10

### Operating system version

Android 5.1.1

### Application version and app store

1.4.27 from GP

### Homeserver

Synapse 1.61.1

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
Looks like we are missing libopuscodec.so lib @fedrunov

**Comment by ouchadam** [comment]
@rkfg are you still experiencing the issue with the latest version of the app (1.4.32)? 

We believe this may have been fixed in 1.4.28 by https://github.com/vector-im/element-android/pull/6489

**Comment by rkfg** [comment]
@ouchadam Thanks, it works now as expected, just tested on the device!

**Comment by ouchadam** [comment]
great to hear, thanks for confirming!
