### ISSUE TITLE
Markdown crash for double dollar

### ISSUE THREAD

**Issue by opk12** [vector-im/element-android#6640]
### Steps to reproduce

Enable Mardown, but not LaTeX math. Send this message.

```
o
c$h
d$$E(D8$$S)
w$P
```

### Outcome

Element crashes.

### Your phone model

Samsung

### Operating system version

Android 7.1.1

### Application version and app store

Element 1.4.25 from F-droid

### Homeserver

Self-hosted Synapse at home

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
great catch, thanks for raising! was able to reproduce locally

```
Thread: pool-20-thread-4, Exception: java.lang.IllegalArgumentException: Parent of block must also be block (can not be inline)
     at org.commonmark.node.Block.setParent(Block.java:12)
     at org.commonmark.node.Node.appendChild(Node.java:39)
     at org.commonmark.ext.maths.internal.DollarMathsDelimiterProcessor.process(DollarMathsDelimiterProcessor.kt:46)
     at org.commonmark.internal.InlineParserImpl.processDelimiters(InlineParserImpl.java:794)
     at org.commonmark.internal.InlineParserImpl.parse(InlineParserImpl.java:162)
     at org.commonmark.internal.ParagraphParser.parseInlines(ParagraphParser.java:53)
     at org.commonmark.internal.DocumentParser.processInlines(DocumentParser.java:422)
     at org.commonmark.internal.DocumentParser.finalizeAndProcess(DocumentParser.java:480)
     at org.commonmark.internal.DocumentParser.parse(DocumentParser.java:117)
     at org.commonmark.parser.Parser.parse(Parser.java:69)
     at org.matrix.android.sdk.internal.session.room.send.MarkdownParser.parse(MarkdownParser.kt:56)
     at org.matrix.android.sdk.internal.session.room.send.MarkdownParser.parse$default(MarkdownParser.kt:48)
     at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory.createTextContent(LocalEchoEventFactory.kt:108)
     at org.matrix.android.sdk.internal.session.room.send.LocalEchoEventFactory.createTextEvent(LocalEchoEventFactory.kt:100)
     at org.matrix.android.sdk.internal.session.room.send.DefaultSendService.sendTextMessage(DefaultSendService.kt:91)
     at org.matrix.android.sdk.api.session.room.send.SendService$DefaultImpls.sendTextMessage$default(SendService.kt:49)
     at im.vector.app.features.home.room.detail.composer.MessageComposerViewModel$handleSendMessage$1.invoke(MessageComposerViewModel.kt:214)
     at im.vector.app.features.home.room.detail.composer.MessageComposerViewModel$handleSendMessage$1.invoke(MessageComposerViewModel.kt:195)
     at com.airbnb.mvrx.CoroutinesStateStore$flushQueuesOnce$2$2.invokeSuspend(CoroutinesStateStore.kt:91)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:920)
     Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@75275aa, java.util.concurrent.ThreadPoolExecutor@972159b[Running, pool size = 4, active threads = 1, queued tasks = 0, completed tasks = 124]]
```
