### ISSUE TITLE
Element keeps crashing when I click "I am the host" in Jitsi widget

### ISSUE THREAD

**Issue by Sojjjik** [vector-im/element-android#6794]
### Steps to reproduce

We have self-hosted Jitsi server. This server is specified in .well-known/matrix/client. So, when I create a video-chat with phone, element uses our self hosted link. On jitsi server we have enabled auth. When you create a video-chat you recieve a message like "we need to wait a host". You can press "I am the host". You just press this button, enter password and that's it. It used to work. Now, when you press "I am the host" element stops working

   1. Create a video conference in element from Android phone. Self hosted jitsi with enabled auth.
   2. Enter to this conference.
   3. Press "I am the host"
   4. Element stops working

When I press "I am the host" from PC, everything works fine.

Thank you!

### Outcome

What did you expect?
Enter to video conference as a host

What happened instead?
Element stops working

### Your phone model

Samsung Galaxy A30

### Operating system version

Android 11

### Application version and app store

Element - 1.4.31, OLM - 3.2.12

### Homeserver

Self-hosted server. server_version "1.64.0"

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Is it possible to provide some logs? Either form logcat, or by performing a rageshake just after observing the crash. Thanks!

**Comment by Sojjjik** [comment]
Thanks for the answer!
I performed rageshake and sent a report. Is this enough? 
I've included a GitHub issue link in description

**Comment by ouchadam** [comment]
thanks for the logs, looks like an internal jitsi(/react) error 

```
Thread: main, Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.facebook.react.uimanager.FabricViewStateManager.hasStateWrapper()' on a null object reference
at com.facebook.react.views.textinput.ReactEditText.updateCachedSpannable(ReactEditText.java:1)
at com.facebook.react.views.textinput.ReactEditText$TextWatcherDelegator.onTextChanged(ReactEditText.java:7)
at android.widget.TextView.sendOnTextChanged(TextView.java:11785)
at android.widget.TextView.setText(TextView.java:6965)
at android.widget.TextView.setText(TextView.java:6761)
at android.widget.EditText.setText(EditText.java:145)
at android.widget.TextView.setText(TextView.java:6713)
at android.widget.TextView.setEditableFactory(TextView.java:6670)
at androidx.emoji2.viewsintegration.EmojiEditTextHelper$HelperInternal19.(EmojiEditTextHelper.java:11)
at androidx.emoji2.viewsintegration.EmojiEditTextHelper.(EmojiEditTextHelper.java:3)
at androidx.appcompat.widget.AppCompatEmojiEditTextHelper.(AppCompatEmojiEditTextHelper.java:3)
at androidx.appcompat.widget.AppCompatEditText.(AppCompatEditText.java:12)
at androidx.appcompat.widget.AppCompatEditText.(AppCompatEditText.java:2)
at androidx.appcompat.widget.AppCompatEditText.(AppCompatEditText.java:1)
at com.facebook.react.views.textinput.ReactEditText.(ReactEditText.java:1)
at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:2)
at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:1)
at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:1)
at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:1)
```

**Comment by Sojjjik** [comment]
Do I need to create a ticket on the jitsi side?

**Comment by ouchadam** [comment]
I'm not familiar with their contribution guidelines as to whether we should open a new issue or bump the previous instance https://github.com/jitsi/jitsi-meet/issues/11375 

another Element related ticket https://github.com/vector-im/element-android/issues/5745
