### ISSUE TITLE
New timeout crash in 1.5.10 (fails to connect to homeserver)

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#7718]
### Steps to reproduce

None. It happens automatically in background. Maybe receiving messages in the background could be a factor.

### Logs

```
FATAL EXCEPTION: main
Process: im.vector.app, PID: 3480
NetworkConnection(ioException=java.net.SocketTimeoutException: failed to connect to matrix.fairydust.space/65.108.140.50 (port 443) from /[localIP:port] after 30000ms)
	at org.matrix.android.sdk.internal.session.filter.DefaultSaveFilterTask.execute(SaveFilterTask.kt:38)
	at org.matrix.android.sdk.internal.session.filter.DefaultSaveFilterTask$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5b4544a, Dispatchers.Main.immediate]
Caused by: java.net.SocketTimeoutException: failed to connect to matrix.fairydust.space/65.108.140.50 (port 443) from /[localIP:port] after 30000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
	at libcore.io.IoBridge.connect(IoBridge.java:180)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:6)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:74)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:178)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:714)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:1079)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:228)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:157)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at org.matrix.android.sdk.internal.network.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:47)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at org.matrix.android.sdk.internal.network.ApiInterceptor.intercept(ApiInterceptor.kt:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:455)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at org.matrix.android.sdk.internal.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at org.matrix.android.sdk.internal.network.TimeOutInterceptor.intercept(TimeOutInterceptor.kt:173)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:150)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

#### What did you expect?

No timeout crashes.

#### What happened instead?

Timeout crashes. No other apparent impact.

### Your phone model

Xiaomi Mi 5

### Operating system version

Android 12 (LOS 19.1)

### Application version and app store

1.5.10 - F-Droid

### Homeserver

matrix.fairydust.space

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by opusforlife2** [comment]
I'm not in airplane mode when this crash occurs, though. It even happens when surfing the web.
