### ISSUE TITLE
App crashes on startup in 1.5.11

### ISSUE THREAD

**Issue by mpeter50** [vector-im/element-android#7763]
### Steps to reproduce

0. I've just updated the app in F-droid
1. I'm starting the app from my launcher
2. The app crashes

#### What did you expect?
I expected the app to remain opened

#### What happened instead?
The app crashes. Mostly a split second after it switches from the splash screen to the room list, but once I was able to read and open the "do you want to submit a bug report?" dialog, which was there because of the crashes in the previous tries.

### Your phone model

Redmi 3S

### Operating system version

Android 6

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by mpeter50** [comment]
I've selected "No" for the question if I will send logs. I would, but currently I don't know how I could.
I'll soon upload the crash stacktrace that the OS has captured, however.

**Comment by mpeter50** [comment]
The crash stacktrace:
```
java.lang.AssertionError: Could not create instance of com.posthog.android.Properties.
java.lang.NoSuchMethodException: <init> [interface java.util.Map]
 at com.posthog.android.ValueMap.getValueMap(ValueMap.java:84)
 at com.posthog.android.payloads.ScreenPayload.toString(ScreenPayload.java:9)
 at java.lang.StringBuilder.append(StringBuilder.java:202)
 at android.os.Message.toString(Message.java:515)
 at android.os.Message.toString(Message.java:486)
 at android.os.BaseLooper.getMessageString(BaseLooper.java:342)
 at android.os.BaseLooper$MessageMonitorInfo.setMonitorMessage(BaseLooper.java:287)
 at android.os.BaseLooper.updateMessageByState(BaseLooper.java:55)
 at android.os.Looper.loop(Looper.java:152)
 at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mpeter50** [comment]
The app is still crashing on startup with version 1.5.26.
The stacktrace is unchanged, except line numbers being slightly different.

**Comment by mpeter50** [comment]
If I clear the data of the app, I can use it until I accept sending usage data, after just having logged in.
If I don't accept sending usage data, I am asked to choose a notification provider, and the list of rooms gets loaded in a few minutes.
If I turn on sending analytics later on, the app crashes again, and I ahve to delete its data to get it to work again.

The reason I'm so insistent on sending data is that I'm using an old system, on an old device (that otherwise works perfectly fine), and I kind of hope that you are seeing that I also have dozens of rooms joined, and it makes synchronization, but also general operation of the app very slow, and also the consumed storage space (data, not just apk) is a lot too.
