### ISSUE TITLE
1.5.11 crashing in 1:1 video call

### ISSUE THREAD

**Issue by rajil** [vector-im/element-android#7817]
Log submitted

**Comment by rajil** [comment]
Crash log submitted with title 'video call crash'.

**Comment by jmartinesp** [comment]
The crash seems to be:

```
12-20 12:54:44.232  3823  3823 E AndroidRuntime: FATAL EXCEPTION: main
12-20 12:54:44.232  3823  3823 E AndroidRuntime: Process: im.vector.app, PID: 3823
12-20 12:54:44.232  3823  3823 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b3ef391 u0 im.vector.app/.core.services.CallAndroidService}
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
12-20 12:54:44.232  3823  3823 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

As far as I can see `CallAndroidService.startCommand` always displays a notification. Maybe we're taking too long to start the foreground service with the notification (I think we have 5s to do that)?
