### ISSUE TITLE
Crash on voice broadcast playback

### ISSUE THREAD

**Issue by yostyle** [vector-im/element-android#7829]
### Steps to reproduce

1. Listen a voice broadcast
2. Move around the middle of the broadcast with the slider

### Outcome

The application crashed

```
2022-12-20 15:57:15.200 27473-27473/im.vector.app.debug E/VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 40105142
    Element Version : 1.5.14-dev [40105142] (G-31540e6d-2022-12-19 19:17:35 +0100)
    SDK Version : 1.5.14 (31540e6d)
    Phone : Pixel 6a (9244662 13 REL)
    Memory statuses 
    usedSize   96 MB
    freeSize   40 MB
    totalSize   137 MB
    Thread: main, Exception: java.io.IOException: Prepare failed.: status=0x1
        at android.media.MediaPlayer._prepare(Native Method)
        at android.media.MediaPlayer.prepare(MediaPlayer.java:1309)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:308)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.access$prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:47)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl$prepareMediaPlayer$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
        at kotlinx.coroutines.CompletableDeferredKt.completeWith(CompletableDeferred.kt:61)
        at org.matrix.android.sdk.internal.session.DefaultFileService.downloadFile(DefaultFileService.kt:213)
        at org.matrix.android.sdk.internal.session.DefaultFileService$downloadFile$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@67beb7f, Dispatchers.Main.immediate]
2022-12-20 15:57:15.201 27473-27473/im.vector.app.debug E/JitsiMeetLogger: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.io.IOException: Prepare failed.: status=0x1
        at android.media.MediaPlayer._prepare(Native Method)
        at android.media.MediaPlayer.prepare(MediaPlayer.java:1309)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:308)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl.access$prepareMediaPlayer(VoiceBroadcastPlayerImpl.kt:47)
        at im.vector.app.features.voicebroadcast.listening.VoiceBroadcastPlayerImpl$prepareMediaPlayer$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
        at kotlinx.coroutines.CompletableDeferredKt.completeWith(CompletableDeferred.kt:61)
        at org.matrix.android.sdk.internal.session.DefaultFileService.downloadFile(DefaultFileService.kt:213)
        at org.matrix.android.sdk.internal.session.DefaultFileService$downloadFile$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@67beb7f, Dispatchers.Main.immediate]
```

### Your phone model

Pixel 6A

### Operating system version

Android 13

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by yostyle** [comment]
@giomfo the application crashes when the player cannot play a chunk. What should we display in this case ?
On iOS we have an error message in the tile.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/1191674/208886309-3300e5af-ddd4-4e91-be62-00e63fa62c65.png">

**Comment by giomfo** [comment]
@yostyle I shared your remark with the design team
We should prevent the application from crashing for the moment, and notify the user about the error by adding a message in the tile or open a dialog until the design for the management of potential errors is provided
Is there already a error message related to the voice messages that we can use?
