### ISSUE TITLE
Background crash - "Software caused connection abort"

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#8014]
### Steps to reproduce

This happened in the background once so far. I don't have any STR yet.

#### What did you expect?

N/A

#### What happened instead?

Crash log:

```
FATAL EXCEPTION: main
Process: im.vector.app, PID: 27495
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:176)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.InputStreamSource.read(JvmOkio.kt:46)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:13)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:31)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:1)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:11)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:12)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:3)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:19)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2ef937, Dispatchers.Main]
```

### Your phone model

Xiaomi Mi 5

### Operating system version

Android 12 (LOS 19.1)

### Application version and app store

1.5.18 - F-Droid

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
Logs are not relevant.
