### ISSUE TITLE
App crashes when trying to send a message

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-android#8206]
### Steps to reproduce

1. Try to send a message

#### What did you expect?

Can send message

#### What happened instead?

App crashes

### Operating system version

11 (API 30) 2108161927-REL

### Application version and app store

1.5.26

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Seems to be caused by the WYSIWYG library:

```
Caused by: uniffi.wysiwyg_composer.InternalException: called Result::unwrap() on an Err value: PoisonError { .. }
at uniffi.wysiwyg_composer.ComposerModel.getContentAsHtml(wysiwyg_composer.kt:169)
at io.element.android.wysiwyg.EditorEditText.getHtmlOutput(EditorEditText.kt:9)
at im.vector.app.features.home.room.detail.composer.RichTextComposerLayout.getFormattedText(RichTextComposerLayout.kt:16)
```
